- gh-pages/api.html
- gh-pages/examples.html
- gh-pages/index.html
- gh-pages/localization.html
Summary of changes are as follows:
- Fix various grammatical and typographical errors in documentation.
- Update documentation to use 'Vue.js' spelling of the library. This matches the official documentation.
- Fix a dead link in documentation for the english messages file.
> Fix documentation errors

- src/listeners.js
As discussed, rather than have "skip" to opt out of certain validations, allow users to choose which events to opt into.
Usage:
<input name="email" v-model="email" data-validate-on="blur">
As opposed to:
<input name="email" v-model="email" data-skip="input">
Advantages:
- Don't need to know the default events, and then opt out of them, just tell the library which events you're interested in
- Allowed opt-in to validation on custom events that may be emitted from other places?  Low use case, but could be handy at times
> Choose validation events to opt into, rather than use disable/skip logic

- __tests__/listeners.js
- src/listeners.js
Custom rules that had `confirmed`, `after` or `before` in the name were being checked if it had a param. Started a test file for `listener.js`.
One thing I noticed is that [listeners.js:107](https://github.com/logaretm/vee-validate/blob/next/src/listeners.js#L107) checks for a named <input> element. Shouldn't this support `<select>` elements as well or are they handled elsewhere?
> Stricter check for field dependency, add listener test file.

- __tests__/errorBag.js
- src/errorBag.js
I added support for `first()` and `has()` only at this point.  Do we need support for any other methods?
It would be easy: `errors.all(':required')` or with a scope, `errors.all('scope:required')`.
I also refactored the `has()` method to use the `first()` method since it was an exact repeat except for the boolean return type. I felt dirty writing the same exact code in two places while implementing this feature. 
Let me know if you want me to change anything.
> Add rule selector for error bag.

- src/errorBag.js
Just making it a little easier to understand. If we always set `scope` when adding it to the error bag, we can get rid of the `scope &&` part of my if. Tests still pass.
```
add(field, msg, rule, scope) {
this.errors.push({ field, msg, rule, scope });
}
```
Thoughts?
> Errorbag first() refactor for readability

- __tests__/validator.js
- src/rules/confirmed.js
- src/validator.js
Laravel looks for a "{fieldname}_confirmation" field when using the confirmed rule, so I made this work the same when no field is explicitly set.
> Auto-detect field when 'confirmed' rule has no target.

- __tests__/errorBag.js
- src/errorBag.js
When working with a CMS based approach you might want to render the
validation messages from fields within the CMS. Currently there is no
possibility to retrieve the first error that occured on a field. This
extention makes it possible.
Example markup:
```
<span v-show="errors.firstRule('email') === 'required'">FROM CMS: Email
is required</span>
<span v-show="errors.firstRule('email') === 'email'">FROM CMS: Email
invalid</span>
```
> Extended the ErrorBag with a method to return the first error type violated

- src/listeners.js
Some rules might be interested in receiving a object as a argument. Deep option is needed so the callback gets triggered when a object property updates.
> Deep watch arguments

- src/listeners.js
If the user explicitly sets a `data-vv-name` it should should have precidence over the `name` attribute.
> Prefer data-vv-name over name attribute

- src/validator.js
The name property is `null` unless aliasing the field name by setting `data-vv-as` attribute
> Fixed bug for function formatErrorMessage

- types/vee-validate.d.ts
This commit fixes the following error:
> ERROR in /path/to/project/node_modules/vee-validate/types/vee-validate.d.ts
(25,17): error TS2304: Cannot find name 'Dictionary'.
A strong type (`Dictionary`) can only be used after it's defined. Since we haven't written definitions for `Dictionary` yet, I've changed the type to `any`.
(Type definitions only exist for `Validator` and `ErrorBag` at the moment.)
> Fix undefined type dictionary [ts]

- src/validator.js
- test/validator.js
Applying a scope when providing an object to validateAll() is not currently possible (when using the Validator object programmatically).
This PR is an attempt at removing this limitation.
> Applying a scope when providing an object to validateAll().

- src/validator.js
Hey guys!
I've just add a reference to Rules setup as a method of Validator object.
So, rules will be available from now on in extend function:
Validator.extend('registrationEmail', {
getMessage: (field) => { return '' }
, validate: (value) => {
return this.validator.**rules**.email(value)
}
});
> Adding rules to Validator object

- src/plugins/date/date_between.js
- test/rules/date_between.js
Expose the inclusivity parameter from the momentjs date_between function
to allow the date_between rule to be right, left or all inclusive
Reference issue #418
> Add inclusivity parameter to date_between rule

- types/vee-validate.d.ts
Minor improvements to TypeScript definitions. Fixes constructor signature not matching the code. Adds the `fieldBag` to the interface.
> Fix constructor signature mismatch. Add fieldBag to interface. (TypeScript definitions)

- types/vee-validate.d.ts
Improvements to TypeScript definitions. Fixes fieldBag types which enables field state checks in typescript.
e.g.:
$validator.fieldBag['field'].valid; // check one field
_.every(this.$validator.fieldBag, (field: FieldFlags) => field.valid); // check all fields with lodash function
> Add type defintions for fieldBag and fieldFlags (TypeScript definitions)

- docs/examples.html
`touched` was mispelled as `tocuhed`, and `isFormDirty()` was mispelled as `isFormDiry`.
> Fix typos within Flags section.

- src/rules/confirmed.js
Currently, the `confirmed` rule only works on inputs with the `name` attribute. This fix allows components with `data-vv-name` to work the same way.
> Fix confirmed rule not working on data-vv-name'd elements

- types/vee-validate.d.ts
I noticed that some of the Typescript definitions had fallen out of sync - this is causing me issues on my current project (I need to `validateAll()` by scope, which the current definitions don't allow).
I've made some tweaks to update the definitions to match how the current code behaves.
> Updated Typescript definitions.

- src/validator.js
Instead, communicate a failure of validation using a param to resolve.
See issue #506
> Don't use reject for expected outcomes.

- src/errorBag.js
I believe this fixes my issue #558. The problem seems to be related to this remark in the Vue documentation:
> Mutation methods, as the name suggests, mutate the original array they are called on. In comparison, there are also non-mutating methods, e.g. filter(), concat() and slice(), which do not mutate the original array but always return a new array. When working with non-mutating methods, you can just replace the old array with the new one.
> 
> You might think this will cause Vue to throw away the existing DOM and re-render the entire list - luckily, that is not the case. **Vue implements some smart heuristics** to maximize DOM element reuse, so replacing an array with another array containing overlapping objects is a very efficient operation.
(emphasis mine)
It seems that these …
> Always modify errorBag in-place. Fixes #558

- types/vee-validate.d.ts
Added missing field to FieldFlags type definition.
This is related to #474 need required flag.
> Add type defintions for required and pending to FieldFlags

- src/classes.js
Close #580
[addInteractionListeners() method](https://github.com/logaretm/vee-validate/blob/830bc9ceb591463b135f14c15270caf374c5ddc2/src/classes.js#L100-L108) is responsible to add input and focus listeners on the element if there are not already registered.
But with current codebase, `this.listeners.input` [is not set to null](https://github.com/logaretm/vee-validate/blob/master/src/classes.js#L86-L90) after listener beeing invoked once for a component, so addInteractionListeners() nevers add the listener back on component.
This patch fix the issue by setting `this.listeners.input` to `null` for components too.
> Fix flags not refreshed after a data change on custom components

- src/errorBag.js
- tests/errorBag.js
Usually, when we build up our mobile application, we don't want to show all of the error to users. 
The error from 'required' rule is useful for validating a form but also disturbing users, you know they can truly see which field is required from their little mobile phone. Only users type wrong characters we want to notice them. 
so, why not add a new function that filters all errors that not match the rule~
> feat: errorbag new function firstNot

- src/index.js
- src/plugins/date/index.js
- src/validator.js
This PR aims to create a standard API to be used with 3rd party plugins that may need to extend the functionality of the plugin.
The `use` method on the top level default module which is the main way to install plugins. It accepts two arguments, the first is the plugin install function, the second is any configuration or dependencies needed to install or configure the plugin.
The install function must have a very specific signature, It should accept at least one argument and at most two arguments. The first argument is called the **installation context**.
It is just a fancy way to say it is an object that wraps most of the dependencies you need to extend vee-validate. Which are: 
- `Validator` class, which can be used to add rules.
- `ErrorBag` class, which you may need to manipulate or …
> Plugin API

- locale/bg.js
i was unable to test it, since i got 
```
You are setting the validator locale to a locale that is not defined in the dicitionary. English messages may still be generated
```
and I am still getting use to VueJS
> added Bulgarian translations

- types/vee-validate.d.ts
I need to access `ErrorBag`'s `items` property because need to get `ErrorField`'s from it and pass to another `ErrorBag` object.
> Add items property to ErrorBag class

- types/vee-validate.d.ts
Usage:
```
Vue.use<VeeValidate.Configuration>(VeeValidate, {
validity: false,
aria: false,
})
```
> Add typing for Configuration

- docs/src/templates/markdown/rules/validations.md
This MR wasn't reflected: https://github.com/baianat/vee-validate/pull/419  
Even after the switch to `date-fns` this still works and is supproted: https://github.com/baianat/vee-validate/blob/master/src/rules/date_between.js
> Update date_between rule docs regarding inclusion functionality

- src/core/generator.js
- tests/generator.js
Hi, Working with vee-validate, I created several scopes using an object position in an array.
Trying to validate with those scopes, some validations failed because of different scope type String vs Number.
I noticed that the first element was using a String scope '0' and the rest numbers 1..n
The change in this PR checked the scope validity, but still allows for the 0 value.
> Support scope value equals 0

- src/core/errorBag.js
- src/core/field.js
- src/core/generator.js
- src/core/utils.js
- src/core/validator.js
- tests/field.js
- tests/validator.js
After allowing 0 scope, I found more places in the code that I neglected.
> Refactore more scope tests to use isNullOrUndefined(scope)

- src/core/field.js
- src/core/generator.js
- src/mixin.js
- tests/generator.js
- tests/mixin.js
Custom components validation has been supported for a while now, but was verbose if the user used custom components as their inputs instead of native HTML5 ones. Mainly because a lot of information must be gathered about these components.
The validator gathered the information using custom `data-*` attributes like `data-vv-name` and `data-vv-value-path`. Which is repetitive if you are going to use components for your validation. Except when using `v-model` which then the plugin uses the model instead as the source of a part of the information, which is the value getter part.
A common solution people tended to navigate to, is to implement a self validating components, which means the directive is used inside the component rather than on it in its parent scope. While this works, it required …
> [WIP] Component Interface

- docs/index.html
- docs/src/templates/markdown/home/config.md
Validity default value has changed with e2edad7fa70853433b98768d2f9f9244b0771da0 but documentation hasnt been updated accordingly.
> Fixed detail in documentation

- types/vue.d.ts
Import statements and **ComponentOptions** changed, in order to support **TypeScript** changes in **Vue** 2.5
check official blog post for more info:
https://medium.com/the-vue-point/upcoming-typescript-changes-in-vue-2-5-e9bd7e2ecf08
> Aument types adapted to support TS changes in Vue 2.5

- docs/src/templates/markdown/rules/validations.md
Updated to new object syntax and added note about escaping
backslashes ('\').
> Updated regex validator docs

- src/core/validator.js
- tests/validator.js
In response to issue #843 
This is another possible implementation where reset returns a promise. Reject is never called since a reset never fails, so the callback seems to be a better implementation
> Implementation Two: Reset returns a promise

- package.json
- src/config.js
- src/core/generator.js
- src/core/utils/index.js
- src/directive.js
- src/install.js
- src/mixin.js
- tests/config.js
- tests/directive.js
- tests/generator.js
- tests/mixin.js
- yarn.lock
Currently `vee-validate` is only usable by using Vue's plugin API
```js
Vue.use(VeeValidate);
```
Which is simple enough for most workflows, however some scenarios require having a rather selective installation, for example you want vee-validate to be working in some components but not others. Which could improve load time when using async components.
Another factor is the global pollution, VeeValidate currently injects a mixin and a directive in all components regardless if they are going to be using it or not, which is unnecessary.
This PR aims to add the ability to install vee-validate manually by converting the directive and mixin to standalone parts, so they can be imported and injected selectively into a component.
```js
import { directive, mixin } from 'vee-validate';
export …
```
> [WIP] Selective Imports

- docs/api.html
- docs/examples.html
- docs/index.html
- src/core/field.js
- src/core/generator.js
- src/core/utils/index.js
- tests/field.js
- tests/generator.js
- tests/utils.js
As mentioned by @ssendev in #620 the validation delay does not make a lot of sense on blur. The primary objective of the delay would pretty much always be to stop error messages while typing. Since the blur event needs to be triggered by the user manually, there is no point in applying the delay there too.
Of course, the topic of #620 originally was more complex: The delay and events should be dynamic based on the status of the field. It makes a lot of sense, but it does require more changes.
Now I will admit, my solution is all but ideal, but it works (locally tested) and it does solve the issue. I do hope it can be improved further (config option, separate delay for blur events, less awful code).
Since the code quality isn't great and I couldn't figure out how to properly test specific …
> Do not apply delay to blur event

- .babelrc
- build/config.js
- build/esm.js
- build/locale.js
- build/minimal.esm.js
- build/minimal.js
- package.json
- src/core/utils/index.js
- yarn.lock
The build scripts, especially main.js, were cluttered and really untidy. The many bundles that were built in main.js were also not logically decoupled, even though they had their own index files. Additionally, the build files were using CommonJS syntax, whereas the rest of the project was using ES6.
I've split up the ``main.js`` build script into it's logical bundles. Each build script now only has one call to ``rollup``. I've also created a ``config.js`` file for shared settings.
```
Old:                  |  New:
------------------------------------------------              
vee-validate          |  vee-validate
+-- build             |  +-- build
+-- main.js       |      +-- config.js
+-- locale.js     |      +-- esm.js
|      +-- locale.js
|      +-- main.js
|      +-- minimal.esm.js
| …
```
> Split up build scripts and move them to ES6

- src/core/validator.js
The global ERROR object keeps references to the errors objects.
This prevent the garbage collector from freeing the memory.
This fix simply check if a window exists (if yes we are running in the browser) else we are in SSR.
Do not add the error object to the ERROR const global variable to allow GC cleanup.
> Fix Memory leak in SSR

- docs/index.html
Removed bracket at the end of the https://unpkg.com/vee-validate@2.0.0-rc.7 url.
> Fixed example on index page.

- package.json
- `@vue/test-utils` is used only for tests
- `babel-plugin-transform-object-rest-spread` is used only for build
> Move dev-only libraries to devDependencies

- flow/validator.js
- src/core/errorBag.js
- src/core/field.js
- src/core/utils/index.js
- src/core/validator.js
- src/directive.js
- src/install.js
- tests/unit/errorBag.js
- tests/unit/utils.js
This PR aims to improve many aspects of the performance issues of this plugin:
> [WIP] Performance improvements

- locale/tr.js
Turkish 've(and)' the conjunction is written in combined. The spelling error was corrected because it was a separate word.
> Fix Turkish conjunction combined spelling mistake

- src/core/errorBag.js
- src/core/utils/index.js
- tests/unit/errorBag.js
This PR refactors the matching behavior of error items to be more re-usable. The matching function will be re-used with `errors.collect` and `errors.remove`.
Also introduces a tiny perf gain with large error bag items count since it doesn't search twice for fields with dots in their name.
closes #1322, closes #1317
> Error Bag consistency fix

- src/core/field.js
- src/rules/confirmed.js
- tests/integration/components/Targets.vue
- tests/integration/target.js
- tests/unit/validator.js
This PR introduces a __BREAKING CHANGE__ related to targeting other fields.
All targets must be a ref. deprecating the use of class, id and name selectors.
- This affects the __confirmed__, __before__, and __after__ rules.
- The `confirmed` rule will no longer fallback to `${field}_confirmation` name targeting if none provided.
- Removes the confusion around the different targeting selector formats since it leaves one universal way to target other fields regardless of their nature.
- SSR friendly since it removes the need for __document__ and __window__ objects. 
Now you should always now have a ref on the target field:
```html
<input type="password" name="password" v-validate="'required|confirmed:password'">
<input type="password" name="confirmation" ref="password">
```
> breaking: deprecate selectors in rules in favor of refs

- types/vee-validate.d.ts
Typescript definition is missing options as a third parameter. Therefore it is not possible to bind target parameter for custom validations such as custom confirmed validator. This fix is to solve this issue in typescript.
> extend method missing options param

- src/core/field.js
- src/core/generator.js
- tests/integration/components/Model.vue
- tests/integration/components/stubs/ChildWithModel.vue
- tests/integration/model.js
This PR aims to improve the way VeeValidate deals with `v-model` bound fields in custom components.
When setting up the field, the plugin will check if the [component customizes its v-model](https://vuejs.org/v2/guide/components-custom-events.html#Customizing-Component-v-model) behavior and use that info to improve the overall detection code. 
Which should eliminate many cases where `data-vv-validate-on` and `data-vv-value-path` is used on components authored by 3rd parties.
Related issues: #1324
> improve model detection

- docs/api/validator.md
This is a required parameter to validate a single field. 
People should be able to learn this from the documentation and not have to debug the source code on their own.
> Include `value` parameter in documentation

- locale/nl.js
To stay consistent with all other translations, every message should end with a dot (.).
Thank you.
> Add dot (.) after email msg was only message not ending with a dot

- docs/api/validator.md
The table of the validator methods was broken and the [signature of the attach method](https://github.com/baianat/vee-validate/blob/c4b47d75e377bc91108dbeb292e40822895fafc6/src/core/validator.js#L173) was not correct.
> docs: fix method signature and docs layout

- types/vee-validate.d.ts
Current implementation does not allow to pass a global config when register the plugin in TypeScript. But with this fix it's possible to do like this:
```typescript
import VeeValidate, { Configuration } from 'vee-validate';
const veeValidateConfig = {
classes: true
} as Configuration;
Vue.use(VeeValidate, veeValidateConfig);
```
> Fixed passing config in TypeScript code

- locale/lv.js
Remove field names surrounding quotes from mesages for latvian translation to become onsistent with other languages translations
> Remove field names surrounding quotes from mesages in Latvian translation

- docs/api/validator.md
Added documentation for resetting field flags that are scoped. Works great in conjunction with solution provided in https://github.com/baianat/vee-validate/issues/564
I'd recommend adding that isDirty() check into the documentation. Possibly into the code itself.
> Added documentation for resetting scoped field flags.

- CONTRIBUTING.md
I found a little issue while trying to run vuepress, it would show an error from a missing file. Then I found out that I needed to run ``` npm run build:esm ``` the avoid this error. 
Well it might help other people in the future.
> Add a guide to execute the vee-validate docs locally. A fix to #1590

- locale/ro.js
The correct parameter to use is 'decimals'.
> Fixed undefined 'decimale' in Romanian locale

- locale/ja.js
Hi. Thanks for your great project. I've noticed that some ja messages are missed so I added.
The following image is just for confirmation.
Confirmed with the following Vue component.
```
<template>
<div id="app">
<div>
<label>_default</label>
<input name="_default" type="text" v-validate="'fail'">
<p>{{ errors.first('_default') }}</p>
</div>
<div>
<label>is</label>
<input name="is" type="text" v-validate="{ is: 'HELLO' }">
<p>{{ errors.first('is') }}</p>
</div>
<div>
<label>is_not</label>
<input name="is_not" type="text" v-validate="{ is_not: 'HELLO' }">
<p>{{ errors.first('is_not') }}</p>
</div>
<div>
<label>length</label>
<input name="length" type="text" v-validate="'length:5'">
<p>{{ errors.first('length') }}</p>
</div>
<div>
<label>length (max)</label>
<input name="length_max" …
```
> Fix ja messages

- docs/api/mixin.md
- corresponding to https://baianat.github.io/vee-validate/api/mixin.html
(The previous PR was closed due to strange behavior of switching base branch but might be this should point to gh-pages branch instead?)
> Fix a wrong link in document

- locale/zh_CN.js
- locale/zh_TW.js
For use of spacing/punctuation or not, I follow existing translation strings in that language.
There can be a one-off revise so wordings within the same language would be more consistent too.
> Add missing zh_TW/zh_CN translations

- types/vee-validate.d.ts
Corresponding to `verify (value: any, rules: string | MapObject)`.
`MapObject -> Object` typing references existing methods,
e.g. dictionary parameter in `static localize` method.
> Add missing ts definition for validator verify method

- flow/validator.js
- src/core/validator.js
- tests/unit/validator.js
- types/vee-validate.d.ts
This introduces an options object as a third parameter that can be passed to the `validator.verify` method, which allows configuring field name, bailing behavior, and providing a value map to cross check for target dependent rules.
The options are:
```js
{
bails: true,
name: '{field}',
values: {}
}
```
closes #1628
> Verify Options

- locale/zh_CN.js
__ 🔎 Overview__
it seems that the zh_CN locale file is not up to date with en locale. This pr corrected two messages for `after` and `before` rules.
> Chinese message for before and after rules.

- types/vee-validate.d.ts
Got a small error using Typescript, the [`validate`](https://baianat.github.io/vee-validate/api/validator.html#api) method's `name` param is supposed to be optional
> types definition : 'validate' name param is optional

- types/vee-validate.d.ts
__ 🔎 Overview__
Adding a custom validator, that uses names arguments, typescript returns an error for type checking.
This PR will just add the `paramNames` to the `ExtendOptions` so that typescript will no longer raise such an error
__ 🤓 Code snippets/examples (if applicable)__
```js
Validator.extend(rule, myValidator, {paramNames: ['rows', 'cols']});
Argument of type '{ paramNames: string[]; }' is not assignable to parameter of type 'ExtendOptions'
```
__✔ Issues affected__
Couldn't find any related issue.
> Add paramNames to ExtendOptions definition

- docs/guide/rules.md
🔎 __Overview__
This PR fixes the documentation for the date_format validation rule that is incorrect and causing questions about its operation. Where "DD/MM/YY" format is displayed, use "dd/MM/yyyy"
See: https://github.com/date-fns/date-fns/blob/master/docs/unicodeTokens.md
> closes #{1619}
> Correct the 'date_format' validation rule example

- types/vue.d.ts
🔎 __Overview__
Feat: It allows to use `this.errors` and `this.fields` directly in TypeScript code, as they are injected via the mixin and documented (see https://baianat.github.io/vee-validate/api/mixin.html). The `$validator` was already exposed.
Allows a method like:
```typescript
public isDirtyAndInError(name: string) {
const field = this.$validator.fields.find({ name });
if (field) {
return field.flags.dirty && this.$validator.errors.has(name);
}
return false;
}
```
to be written as:
```typescript
public isDirtyAndInError(name: string) {
return this.fields[name] && this.fields[name].dirty && this.errors.has(name);
}
```
Fixes #1704
> Add errors and fields to the Vue typings

- types/vee-validate.d.ts
🔎 __Overview__
It allows to use the `mapFields` helper into the `Component` decorator
```typescript
@Component({
computed: {
form: mapFields(),
...mapFields(['login', 'password']),
...mapFields({
name: 'login',
}),
},
})
export default class Login extends Vue {
```
As discussed in #1705
Note that it could be more strictly typed, but I'm not sure about what the return type should be. It at elast allows to compile TS code that use `mapFields`.
> Add mapFields helper to the typings

- src/core/validator.js
- tests/unit/validator.js
🔎 __Overview__
> This PR fixes the bug #1714.
> fixes #1714
> Fix validator.reset not respecting vmId when clearing errors (#1714)

- locale/pl.js
- package.json
- yarn.lock
🔎 __Overview__
Ex (Locale):
> This PR changes the PL locale messages style because the current version has no variations for specific cases. It's a simple way to use nouns with numbers in Polish correctly.
```js
min: (field, [length]) => `Pole ${field} musi być długie na co najmniej ${length} ${characterLabel(length)}.` // if length = 3 / characterLabel = 'znaki', if length = 5 / characterLabel = 'znaków'
```
none
> polish plurals

- locale/bg.js
🔎 __Overview__
Ex (Locale):
> This PR changes the Bulgarian error message for length because it was grammatically incorrect and didn't make any sense.
> Fix gramatically incorrect error message in Bulgarian locale

- src/core/validatorDecorator.js
- tests/unit/validatorDecorator.js
According to docs *scope* parameter in detach() method is optional, but in code it's required actually. 
If we want to remove field without scope, we must do this (which is not obvious): 
```js
validator.detach('field', null);
```
This pull-request makes *scope* parameter optional, so we also can do this:
```js
validator.detach('field');
```
Possible related issue #782
> fix: make detach() scope parameter optional in validatorDecorator

- docs/guide/classes-and-styling.md
🔎 __Overview__
Docs were incorrect on this part, using `true` instead of `false` to disable aria-* attributes
> docs: correct value to disable aria-* attributes

- docs/api/directive.md
- src/components/provider.js
- src/core/field.js
- src/core/resolver.js
- src/core/validator.js
- tests/integration/components/Persist.vue
- tests/integration/persist.js
🔎 __Overview__
The `.persist` directive (as discussed in #1799 between @HapLifeMan & @logaretm) consists in keeping the validation state (field instance & associated errors) when the field is removed from the DOM/component, allowing multi-views forms to use vee-validate properly, without missing errors from previous views.
I also implemented corresponding tests, & written docs about the feature.
🤓 __Code snippets/examples__
```vue
<template>
<div>
<div v-if="displayField">
<input v-model="email" v-validate.persist="'required|email'" data-vv-validate-on="input" name="email" type="text">
</div>
<label><input type="checkbox" v-model="displayField"> Display the field</label>
<div>{{ errors.first('email') }}</div>
</div>
</template>
<script>
export default {
data: () => ({
email: '', …
```
> feat: added persist directive (fixes #1799)

- docs/guide/conditional-and-looping-inputs.md
Specifically in the `v-if` section.
🔎 __Overview__
This PR fixes a typo in the Conditional and Looping guide within the docs.
No issue impacted
> Fixed typo in conditional and looping guide

- src/core/validator.js
🔎 __Overview__
This is a fix related to my previous PR (persist directive), I wasn't aware of scope in the old-field search & replacement. Only `.persist` scoped fields were affected, so I guess that nobody had the time to experience & notice it. :smile:
> fix: use scope in old-field search (persist directive)

- docs/guide/custom-rules.md
- docs/guide/rules.md
- locale/en.js
- locale/fr.js
- src/components/provider.js
- src/core/field.js
- src/core/ruleContainer.js
- src/core/validator.js
- src/rules/index.js
- src/rules/required_if.js
- tests/integration/components/ComputesRequired.vue
- tests/integration/computesRequired.js
- tests/unit/rules/required_if.js
This PR add the `computesRequired` rule option, which allows to implement required-like rules based on complex conditions. I've also implemented the `required_if` rule to demonstrate how to use the option for custom (or official) rules to come.
The `required_if` rule is based on the laravel validation rule (https://laravel.com/docs/5.7/validation#rule-required-if). It has been requested by other folks in issues (#1201, #41).
I also added en & fr locales associated to the `require_if` rule.
And the proper tests & docs. ;)
Here is the `required_if` code:
```js
const validate = (value, [otherFieldVal, ...possibleVals] = []) => {
let required = possibleVals.includes(String(otherFieldVal).trim());
if (!required) {
return {
valid: true,
data: {
required
}
};
}
let invalid = (isEmptyArray(value) …
```
> feat: added `computesRequired` rule option and `required_if` rule

- types/vee-validate.d.ts
added `computesRequired` to `Validator.extend` available options, which allows a rule to determine if the field is required after merging #1812
> feat: added computesRequired

- docs/guide/displaying-errors.md
> Syntax error in a label in documentation

- src/core/resolver.js
This disables aria attributes and validity API for custom components as they are not applicable to them anyways, they cause an issue for IE Edge when trying to resolve a component value upon manual validation.
closes #1854
> fix: disable aria and validity for components

- docs/examples/radio.md
🔎 __Overview__
Documentation showed the use of an "in" operator but this does not exist. The operator should be "included".
Ex (Feat):
> This PR fixes the radio button documentation example.
No issues affected.
> Validator "in" should be "included"

- src/utils/index.js
- tests/unit/utils.js
> fix: added NaN check for directive render loops closes #1873

- types/vee-validate.d.ts
This fixes the `VerifyOptions` for the `Validator.verify` method and marks its properties as optional instead of required.
closes #1845
> fix: VerifyOptions TS properties should be optional closes #1845

- docs/guide/components/validation-observer.md
- docs/guide/components/validation-provider.md
- src/components/observer.js
- src/components/provider.js
- src/utils/index.js
This PR allows observers to be nested under other observer, parent observers are able to present a state of the entire child observer/provider tree.
Parent observers are able to trigger `validate` and `reset` on child observers and providers.
closes #1879
> Feat nested observers

- docs/guide/displaying-errors.md
🔎 __Overview__
FIX:
> This PR fixes the a ul tag that has no matching end tag
> Tag list fix

- docs/guide/events.md
Usually developers will just copy this lines of code so I suggest it is better to use proper variable names
for good practice.
> Change variable to valid as a better example

- docs/guide/localization.md
Currently the example won't work without the line:
159: i18n.locale = "en"; // set a default locale (without it, it won't work)
For description look here https://github.com/baianat/vee-validate/issues/1891
and/or here
https://stackoverflow.com/questions/55045730/vue-i18n-integration-by-vee-validate-not-working-as-described-in-the-documentati
🔎 __Overview__
Ex (Feat):
Ex (Locale):
```js
// some code
```
> Correct the example VueI18n Integration

- src/components/provider.js
This PR forces validation triggered by events to wait until the nextTick, this allows validation providers to validate checkboxes values after they've been stabilized.
closes #1900
> fix: event value mismatch with model value for checkboxes  (fix #1900)

- docs/guide/components/validation-provider.md
- docs/guide/custom-rules.md
- docs/guide/rules.md
Enhanced some notes on cross-field validation and the locating methods used by the directive or the providers.
> docs: updated the usage of vid for cross-field validation with providers

- src/components/provider.js
- src/core/field.js
- src/core/resolver.js
- tests/unit/component.js
This PR forces the validation provider and the directive to not validate the cross-field targets until they have been interacted with or if validation was triggered manually at least once.
This solves the "aggressive" behavior when the user has only interacted with one of the two confirmed inputs for the first time.
closes #1902, closes #1869, closes #1765
> Feat cross field validation behavior

- docs/api/validator.md
- docs/guide/components/validation-provider.md
- src/components/provider.js
- src/core/validator.js
- tests/unit/validator.js
- types/vee-validate.d.ts
This PR adds `failedRules` to the `Validator.verify` result and to the ValidationProvider slot-scope props, which is very useful if someone wants to do UI customizations based on the failed rules.
```vue
<ValidationProvider rules="required|email" name="field">
<div slot-scope="{ errors, failedRules }">
<input type="text" v-model="value">
<span v-if="failedRules.required">Come on, this is required!</span>
<span v-if="failedRules.email">Have you ever seen an email like the one you just wrote?</span>
</div>
```
closes #1898
> Feat verify failed rules

- docs/.vuepress/config.js
- docs/guide/components/validation-provider.md
- docs/guide/interaction.md
- src/components/provider.js
- src/config.js
- src/modes.js
- src/plugin.js
- tests/unit/component.js
🔎 __Overview__
Checklist:
This PR adds the ability to specify an interaction mode as formalized by [simple-vue-validator](http://simple-vue-validator.magictek.cn/#m_modes).
There are 4 modes implemented for you by default:
- aggressive: this is the default mode and it always validates on `input`.
- passive: doesn't validate on any event, so you can only validate manually.
- lazy: validate on `change`.
- eager: validates on `change` for the first time, then if the field is invalid it will validate on `input`. If the field turns valid again it will go back to validating on `change`. This was a popular request by many developers #1426.
You can customize the mode for each validation provider using the `mode` prop:
```vue
<ValidationProvider rules="required|email" mode="eager">
<div …
```
> Feat interaction modes

- src/rules/numeric.js
- tests/unit/rules/numeric.js
This adds basic Arabic numeric support to the `numeric` rule
closes #695
> feat: added arabic numerics to the numeric rule

- src/core/validator.js
This PR fixes a long-standing issue where rules imported from the `dist/rules.esm` would not behave the same due to them having the rules options embedded in them. This causes the validator to not properly set the target fields nor correctly validate date values.
closes #1866, closes #1732
> fix: handle embedded rules options imported from minimal bundle

- docs/.vuepress/enhanceApp.js
- docs/guide/components/validation-observer.md
- docs/guide/components/validation-provider.md
- docs/guide/rules.md
- src/components/observer.js
- src/components/provider.js
- src/utils/vnode.js
- tests/unit/component.js
This PR fixes the full support with `v-slot` which is the new way to use slots, and scoped slots.
Now both `ValidationProvider` and `ValidationObserver` are **no longer renderless** because the v-slot can be used on `template` and cannot be used on HTML elements. Which means the providers will be getting child roots more often than not. a `span` is used by default to render the providers or the observers. This makes the validation components fully compliant with `v-slot` semantics.
The rendered tag can be customized using the `tag` prop on either component, which makes the observer more useful by rendering it as a `form` tag instead of nesting a child form tag.
While I loved the idea to keep those components renderless, it would introduce SSR issues with frameworks like Nuxt where …
> feat: full v-slot support

- .eslintrc.json
- src/components/provider.js
This PR changes how the providers `rules` watcher is implemented by only triggering validation only when the old rules value is different than the current one.
This didn't work properly with object syntax for rules and using the `observers` slot scope, which caused infinite render loop due to the rules object being having different reference each time a re-render happens.
This is similar to the directive's `update` loop having infinite loop due to the object reference not being the same which is the nature of inline values in Vue in general.
This is fixed by only allowing the component to re-validate only if the new rules object have different configuration than the old one.
this also should improve the performance slightly in other cases.
closes #1920
> fix(perf): cap the rules watcher frequency

- docs/guide/components/validation-provider.md
- types/vee-validate.d.ts
This adds public data/methods typings to the validation provider and observer components so that they can be used as cast targets for typescript when using `refs`.
```vue
<template>
<div id="app">
<ValidationProvider ref="someRef" rules="required">
<div slot-scope="{ errors }">
<input v-model="model" type="text">
<div v-if="errors" v-text="errors[0]"></div>
</div>
</div>
</template>
<script lang="ts">
import { Component, Vue } from "vue-property-decorator";
import HelloWorld from "./components/HelloWorld.vue";
import { ValidationProvider, ValidationObserver } from "vee-validate";
@Component({
components: {
ValidationProvider
},
mounted() {
(this.$refs.someRef as ValidationProvider).applyResult({
errors: ["this is a backend error"],
valid: false,
failedRules: {}
});
} …
```
> feat: added ts typings for validation provider and observer components

- docs/guide/rules.md
- locale/en.js
- src/rules/index.js
- src/rules/ip_or_fqdn.js
- tests/unit/rules/ip_or_fqdn.js
This adds a validator rule `ip_or_fqdn` which requires the field to be a valid IPv4 or IPv6 address, or a valid fully-qualified domain name.  Patch include documentation, tests, and an error message in the English locale.  I don't know any other languages well enough to write error messages for them.
> Add an ip_or_fqdn validator

- docs/guide/components/validation-provider.md
- src/components/observer.js
- src/components/provider.js
- tests/unit/component.js
This PR implements the `.persist` modifier behavior for the Validation Provider component, the current implementation uses a `persist` prop and has a few conditions to get it working properly.
Your provider __must__ be inside an __observer__ scope and must have a `vid`, as it will be the only way to identify the field, a warning message would be printed in dev mode to aid the use of this feature when not configured properly.
```vue
<div id="app">
<ValidationObserver>
<div v-if="!isHidden">
<ValidationProvider
rules="required|min:3|max:6"
vid="myfield"
v-slot="{ errors }"
:persist="true"
>
<input type="text" v-model="value">
{{ errors[0] }}
</div>
</ValidationObserver>
<button @click="isHidden = !isHidden">Toggle</button>
</div>
```
We could remove the __observer__ …
> [feat] persist provider state

- docs/configuration.md
🔎 __Overview__
Adds missing comma to the config object in configuration.md
> Adds missing comma in configuration.md

- src/utils/vnode.js
🔎 __Overview__
If the select use an attribute (like `name` or `id`) the `getInputEventName` method see the `select` like a base `input`
Ex (Feat):
> This PR fixes the #1936.
> closes #1936
> [#1936] added: use change input event if vnode.tag is equal to 'select'

- locale/pt_BR.js
- locale/pt_PT.js
This PR adds the message translations in pt_PT and pt_BR of the rule: [is](https://baianat.github.io/vee-validate/guide/rules.html#is).
> Translate the "is" rule messages in pt_PT and pt_BR languages

- locale/ru.js
🔎 __Overview__
This PR changes the ru locale `decimal` messages style because: it's wrong grammatical case if there is no digits
nope
> fix ru locale grammatical case

- docs/guide/rules.md
🔎 __Overview__
Fix `required_if` code snippet to match text explanation adding `FM` to required condition
```js
<input v-validate.immediate="'required_if:country,US,FM'" data-vv-as="state" :class="{'input': true, 'is-danger': errors.has('state_field') }" name="state_field" type="text" placeholder="State">
```
> Update rules.md required_if code snippet

- src/utils/index.js
- tests/unit/utils.js
🔎 __Overview__
Recently, I had an error
`Uncaught TypeError: Cannot use 'in' operator to search for 'someKeyHere' in`
While I debug things, I think it's better to have a full path as part of stack trace.
WDYT ?
Ex (Feat):
Ex (Locale):
```js
// some code
```
> Add verbose error when path isn't within object

- types/vee-validate.d.ts
🔎 __Overview__
Fixes Statements are not allowed in ambient contexts when using typescript
> Fix typescript error

- src/core/validator.js
🔎 __Overview__
It was not possible to do a `validateAll` toward a list of fields while specifying their scope. Not even with a common scope.
This PR will allow to do that with an array-typed argument: objects will be treated as matchers, with a default `vmId` assignment. Strings are treated like before (non-breaking): as name-targetted values.
🤓 __Code snippets/examples__
```js
await this.$validator.validateAll([
'my_field_name',
{ name: 'my_scoped_field_name', scope: 'my_scope' },
{ name: 'my_scoped_field_name', scope: 'my_scope2' },
'my_other_field_name'
// etc.
]);
```
So bad that I'm coming just 4 hours after the last release :(
> feat: handle array of objects in validateAll

- locale/de.js
Ex (Locale):
> This PR adds the german message for required_if, since it is missing.
> Translated required_if to german

- package.json
- src/localization/i18n.js
Flat array params for detect one or more params
🔎 __Overview__
As reported in the issue #1607, vue-i18n default adapter has a limitation. When multiple params are required (e.g.: min, max) both are sended like a only one array. This is a weird behavior, because the pattern adopted (and also explained by some developers that use vue-i18n) is that each value is an argument. Vue-i18n lib has an abstraction for array-like objects thats works fine.
> fix: enable pass args to the i18n messages

- src/rules/ip_or_fqdn.js
- tests/unit/utils.js
🔎 __Overview__
> This PR fixes the execution of `yarn lint` at root level:
```sh
yarn lint
yarn run v1.12.1
$ eslint src tests --fix
vee-validate/tests/unit/utils.js
278:10  error  Unexpected console statement  no-console
✖ 1 problem (1 error, 0 warnings)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command
```
> fix: make `yarn lint` not fail

- src/core/fieldBag.js
- src/core/validator.js
- src/directive.js
🔎 __Overview__
This PR improves the performance of finding fields by id, using a plain object as a map to link ids to items faster than by looping over the array and matching.
In my profiling of large forms with many fields with validation, the repeated looping over the fields triggered by `findField()` in `src/directive.js` had a serious performance impact that showed up as hundreds of milliseconds in my profiling. 
This simple optimization removes that bottleneck.
> feat: optimize finding fields by id

- src/rules/decimal.js
- src/rules/email.js
- src/rules/length.js
- src/rules/max.js
- src/rules/max_value.js
- src/rules/min.js
- src/rules/min_value.js
- src/rules/required.js
- src/rules/url.js
🔎 __Overview__
This PR makes sure to only pass cloned `options` to [validator.js](https://github.com/chriso/validator.js) since they get extended by the default options.
The `email` validator code is made more robust by checking if the `value` is an Array when `multiple` is set and `multiple` is exclude from the `options` passed to the `isEmail()` validator.
Also make sure to use `isNullOrUndefined()` util in rules wherever possible.
Closes #2018.
> fix(rules): clone options passed to `validator.js` + code tweaks (closes #2018)

- src/rules/dimensions.js
- src/rules/ext.js
- src/rules/image.js
- src/rules/mimes.js
- src/rules/size.js
🔎 __Overview__
Adds support for single file in `ext` validation rule.
https://jsfiddle.net/nxwb34hq
closes https://github.com/bootstrap-vue/bootstrap-vue/issues/3128
> Single file support

- src/rules/dimensions.js
- src/rules/ext.js
- src/rules/mimes.js
- src/rules/size.js
- src/utils/index.js
- tests/helpers/index.js
- tests/unit/utils.js
🔎 __Overview__
This is a follow-up PR to #2031 and introduces a new `ensureArray()` util to create an array from a single object like an `File` or an array-like object like an `FileList`.
Tests for the new util are also added and it's used in any rule that handles files.
> fix(rules): improve file/files handling

- types/vee-validate.d.ts
Hello,
This PR fix the types definition for allow return object in `validate`. This is applicable for example for rules `dimensions` and `required_if`.
Thanks.
> fix(types): allow return object on RuleValidate

- src/rules/decimal.js
- tests/unit/rules/decimal.js
🔎 __Overview__
This PR  adds/fixes the scientific/exponential notation in the decimal validator for very large and small numbers. e.g. 1.3e-13, 4e15, 6.5e12, etc.
> fix: add exponential notation to decimal rule

- src/plugin.js
🔎 __Overview__
This fix addresses an issue occurring at i18n locale change when you use locale lazy loading.
Because, since the initial merge doesn't have the switched language in memory, it needs to be merged again when the locale change event is received.
> fix: merge dictionary on locale change

- src/core/validator.js
🔎 __Overview__
The purpose of `useConstraintAttrs` is to consider attrs values, in my opinion it should also include the `disabled` attr in the shouldSkip function.
> fix: skip disabled fields only when useConstraintAttrs is enabled

- types/vee-validate.d.ts
🔎 __Overview__
It's redundant to set flags that has default value in TypeScript.
Ex (Feat):
This PR fix FieldFlags type to omit flags that has default value.
In TypeScript:
```ts
this.$validator.flag('field', {
valid: false,
dirty: true
});
```
closes #2078
> Make flags optional

- docs/api/errorbag.md
1. It's no clear for `bag.add({field: 'name'})` will not work if not add  `msg: 'text'`
2. docs for error bug don't contain `firstRule` method desc
> Update errorbag.md 

- types/vee-validate.d.ts
🔎 __Overview__
This PR fix the result of RuleValidate for allow return multiple results (like results in [dimensions rule](https://github.com/baianat/vee-validate/blob/master/src/rules/dimensions.js#L23))
```ts
Validator.extend('max_dimensions', {
getMessage: (field, [width, height]): string =>
`The ${field} field must be UP TO ${width} pixels by ${height} pixels.`,
validate (files, args) {
const [width, height] = args as string[]
const images = ensureArray(files).filter((file): boolean => imageRegex.test(file.name))
if (images.length === 0) {
return false
}
return Promise.all(images.map((file): Promise<ResultObject> => validateImage(file, width, height, true)))
}
})
```
> fix(types): allow return array of result

- types/vee-validate.d.ts
🔎 __Overview__
This PR fixes the bug.
When we create custom rule without arguments we can call without pass args.
```ts
const validate: RuleValidate = (value): boolean => {
if (isNullOrUndefined(value)) {
value = ''
}
if (Array.isArray(value)) {
return value.every((val): boolean => validate(val) as boolean)
}
return semverRegex.test(value)
}
```
> fix(types): allow empty args

- locale/en.js
🔎 __Overview__
This PR improves EN localization.
I think the translation of the `digits` is not good.
Ex (Locale):
> This PR changes the EN messages style because wrong typo
> Fix wrong typo in the translation

- types/vee-validate.d.ts
🔎 __Overview__
This PR updates the type of `ClassNames` to make every field optional.
AFAIK, it is possible to only declare:
```typescript
Vue.use(VeeValidate, {
classes: true,
classNames: {
invalid: 'is-invalid',
},
});
```
without having to declare every classes.
The current typings don't allow that.
The PR makes every class optional, making such a configuration possible.
> fix(types): class names are not all mandatory

- src/utils/index.js
🔎 __Overview__
isNaN function has not been implemented correctly and it leads to directive doesn't be notified about changes in update hook.
Ex (Feat):
> This PR fixes the IE bug.
> Update hook in IE does not work.

- locale/ar.js
- locale/ca.js
- locale/cs.js
- locale/da.js
- locale/de.js
- locale/el.js
- locale/en.js
- locale/es.js
- locale/fi.js
- locale/he.js
- locale/hr.js
- locale/hu.js
- locale/id.js
- locale/ka.js
- locale/lt.js
- locale/nb_NO.js
- locale/nl.js
- locale/nn_NO.js
- locale/pl.js
- locale/pt_PT.js
- locale/ro.js
- locale/sk.js
- locale/sl.js
- locale/sq.js
- locale/sr.js
- locale/sr_Latin.js
- locale/vi.js
- locale/zh_TW.js
🔎 __Overview__
This is a followup to #1832 where I fixed all the double space in messages... except in `en` locale.
I realized it's because I searched and replaced the condition everywhere, but `en.js` uses a different check than the other locales.
So this PR has two commits:
- one that use the same condition in every locale
- one that removes the extra space for `en` locale
> fix: double space character in decimal message

- docs/guide/components/validation-observer.md
- docs/guide/components/validation-provider.md
- src/components/observer.js
- src/components/provider.js
- src/utils/vnode.js
- tests/unit/component.js
🔎 __Overview__
The validation components are considered to be `Provider` in terms of design and functionality, but it doesn't make much sense to allow them to render anything of their own (`span` by default). But it is required due to the limitations of the Vue rendering engine not allowing multiple root nodes in a component.
This PR adds a `slim` prop to force the components to be renderless, they will only render the first child in their slot. This is inspired by the `slim` prop in [vue-portal](https://github.com/LinusBorg/portal-vue)
When Vue 3.0 comes out we might switch to renderless by default if possible since fragments will allow us to have multiple root nodes.
```vue
<ValidationObserver v-slot="ctx" slim>
<form></form>
</ValidationObserver>
```
closes #2072
> [feat] add `slim` prop to force renderless rendering

- src/components/observer.js
- tests/unit/component.js
🔎 __Overview__
The `persist` prop behavior is not the same as the directive one, the errors and validations state should still be observed inside the observer slot props.
closes #2089
> [fix] `Observer` should have errors for persisted fields

- types/vue.d.ts
🔎 __Overview__
remove unuse parameter
`ErrorBag` and `FieldFlagsBag ` are removed https://github.com/baianat/vee-validate/commit/fedea704e01aaa64749c04c891b74c1be6d70c12
> fix: vue types unuse parameter

- types/vee-validate.d.ts
Hello,
This PR fix an missing options on extend (immediate and isDate) and fix wrong type/syntax for `computesRequired` and `initial`.
Thanks.
> fix(types): add missing options on extend

- src/localization/default.js
- tests/unit/localization/default.js
Fix:
If you set a custom message with setMessage and no message object exists you get an error
> Create a empty messages object when not exists

- docs/guide/rules.md
🔎 __Overview__
This documentation PR adds a missing "separator" param for the decimal rule.
> docs: add missing separator param for decimal rule

- docs/guide/components/validation-provider.md
🔎 __Overview__
Ex (Feat):
> This PR fixes the missing `slim` prop in renderless code exaple in `ValidationProvider`.
> Add missing `slim` prop to renderless code example

- locale/ja.js
Made 'inclusion' in the 'after' and 'before' messages.
🔎 __Overview__
This PR is changing two messages for Japanese users.
> fix: update ja locale

- docs/guide/syntax.md
Fixes some spelling errors in the syntax doc. Specifically on lines 26 and 28.
> Fix minor spelling errors in syntax.md

- types/vee-validate.d.ts
Not much more to say about it, this flag was missing in the typings.
> Added missing changes flag in FieldFlags definition

- docs/README.md
Simple grammar fix when opening the initial docs page.
🔎 __Overview__
Important because there's a typo right on the docs homepage! :)
Ex (fix):
> This PR improves the homepage documentation 3.x warning.
> Typo in 3.x docs warning: "this is a the docs"

- docs/guide/validation-observer.md
🔎 __Overview__
One of the examples has an "await" operator inside a function missing the "async" declaration.
> Missing an "async" declaration

- locale/pt_BR.json
- locale/pt_PT.json
The `{target}` doesn't make sense anymore in the messages. Just for record, the same occur in the following languages.
- ca
- da
- el
- fi
- fr (also in the `required_if` rule)
- id
- it
- ka
- pl
- ru
- sv
- vi
- zh_CN
- zh_TW
> Correction in the translation of "confirmed" rule for pt_BR and pt_PT

- docs/api/rules.md
Corrects a typo in the example of the alpha_spaces rule.
> docs: fix alpha_spaces rule example

- docs/guide/validation-provider.md
🔎 __Overview__
I was reading documentation of new version, and found usage of old syntax. As I know, in v3 there is no `flags` property available, instead flags are directly available.
> Fix example from using v2 syntax

- locale/it.json
🔎 __Overview__
From the `it.json` file were missing some translations of the available validation rules.
None.
> fix: missing validation rule keys in locale file

- src/rules/alpha.ts
- src/rules/alpha_dash.ts
- src/rules/alpha_num.ts
- src/rules/alpha_spaces.ts
- src/rules/between.ts
- src/rules/confirmed.ts
- src/rules/digits.ts
- src/rules/dimensions.ts
- src/rules/email.ts
- src/rules/excluded.ts
- src/rules/ext.ts
- src/rules/integer.ts
- src/rules/is.ts
- src/rules/is_not.ts
- src/rules/length.ts
- src/rules/max.ts
- src/rules/max_value.ts
- src/rules/mimes.ts
- src/rules/min.ts
- src/rules/min_value.ts
- src/rules/numeric.ts
- src/rules/oneOf.ts
- src/rules/regex.ts
- src/rules/required.ts
- src/rules/required_if.ts
- src/rules/size.ts
- src/types.ts
🔎 __Overview__
This PR fixes the bug of types on rules. Some rule could not be use in typescript like `ext` or `alpha`.
_Note : for the rule with type of `value` to any or rule with type `ValidationRuleFunction` it's just because i don't know what is the type excepted._
```ts
import { extend } from 'vee-validate'
import { ext } from 'vee-validate/dist/rules'
extend('ext', ext)
```
This code is now work correctly.
> closes #2289
> fix(types): use right types for rules

- src/utils/vnode.ts
- tests/providers/provider.js
🔎 __Overview__
This PR makes dynamic required on input dom elements possible to be disabled
```js
{
data: () => ({ val: '1' }),
template: `
<ValidationProvider v-slot="{ errors }">
<input type="text" :required="false" v-model="val">
<p id="error">{{ errors[0] }}</p>
`
}
```
> closes #2314
> #2314 Fix required is explicit false

- docs/guide/advanced-validation.md
- docs/guide/basic-validation.md
- src/types.ts
- src/validate.ts
- tests/extend.spec.js
🔎 __Overview__
This PR allows returning templated strings from the validation functions directly, leading to easier and more dynamic messages.
closes #2327
> [feat] allow strings to be returned in rule validation functions

- src/modes.ts
🔎 __Overview__
(SetInteractiveMode)
This PR fixes the bug by adds `?` to make implementation parameter of setInteractiveMode to be optional parameter
```js
export const setInteractionMode = (mode: string, implementation?: InteractionModeFactory) => {
```
> closes #2351
> In setInteractionMode function, implementation parameter should be optional parameter

- src/components/common.ts
- src/components/withValidation.ts
- src/utils/vnode.ts
- tests/helpers/ModelComp.js
- tests/providers/provider.js
**First commit**
The first commit is to fix the lint staged checks.
The test is removed because the _test function always returns an object. See: https://github.com/logaretm/vee-validate/blob/7041538067bfc4e3397abf46545ba4256e68d634/src/validate.ts#L190
**Second commit**
See  #2353 for the issue.
> closes #2353
> Fix: Validation not working when using model less validation with a default value.

- docs/guide/displaying-errors.md
- src/validate.ts
- tests/validate.spec.js
🔎 __Overview__
This PR adds functionality to show any related target field names using `{_target_}` or for multiple targets `{_fooTarget_}`, `{_barTarget_}`, ... 
```js
test('fills target field placeholder', async () => {
const names = { foo: 'Foo', bar: 'Bar', baz: 'Baz' };
const values = { foo: 10, bar: 20 };
const rules = 'confirmed:foo';
const options = {
name: names.bar,
values,
names
};
const result = await validate(values.bar, rules, options);
expect(result.errors[0]).toEqual('Bar must match Foo');
});
```
See tests in:
- https://github.com/davestewart/vee-validate/blob/feature/add-target-placeholder/tests/validate.spec.js#L25-L55
closes #2290
> feat: add target field placeholder

- src/validate.ts
🔎 __Overview__
This PR optimises generation of error messages where there are 0 or 1 targets 
Should very-slightly improve validation speed for arrays of models with cross-field dependencies
> perf: optimise error message generation for targets

- src/utils/index.ts
- tests/validate.spec.js
🔎 __Overview__
This PR allows having empty pipes in string rules and aims to close #2386
```
||||required
```
closes #2386
> fix: allow empty rules expressions

- src/components/common.ts
🔎 __Overview__
Fixes a bug introduced by #2355 where a value of `undefined` would be skipped.
closes #2388
> fix: remove uneeded check when provider re-renders closes #2388

- src/utils/events.ts
- tests/providers/provider.js
🔎 __Overview__
This PR handles both `v-model.trim` and `v-model.number` modifiers, The `ValidationProvider` component uses both `v-model` and `input` event to keep the value tracked, but when one of the two modifiers used, it will end up with 2 different values between re-renders, causing stuff like `eager` mode to break due to it thinking the value changed already in-between the renders.
This PR enhances the value normalization, by casting the value to number using `parseFloat` when the number modifier is used. And `String.trim` if the trim modifier is used.
closes #2403
> fix: handle `v-model.trim` and `v-model.number`

- locale/fr.json
🔎 __Overview__
(Locale):
This PR changes the fr messages for confirmed because the confirmation message showed up the hidden password.
> Correction in the translation of "confirmed" rule for fr

- docs/guide/validation-provider.md
A `</template>` tag is missing in one of the examples which would cause issues when copy/pasting.
> Missing template closing tag

- docs/guide/a11y.md
The documentation said that `ValidationProvider` exposed `aria` in it's scope. Changed that to `ariaInput`.
> Fixed a simple typo

- docs/guide/validation-provider.md
- src/components/Observer.ts
- src/components/Provider.ts
- src/types.ts
- src/utils/index.ts
🔎 __Overview__
This PR adds new flags that have been heavily requested.
The provider and observer will now get those two new flags:
- `passes`: which combines both `valid` and `validated` flags.
- `failed` which combines both `invalid` and `validated` flags.
closes #1692 closes #2325
> feat: added `passed` and `failed` flags

- src/components/Provider.ts
- src/utils/index.ts
- src/utils/rules.ts
- src/utils/vnode.ts
- src/validate.ts
🔎 __Overview__
Before starting on a couple of new features, this PR feature brings consistency to the kitchen sink of `utils/index.ts`:
Consistency:
- moved all `is*` functions together
- moved collection and array functions together
- made all functions a consistent `function fnName () { ... }`
Organisation:
- moved rules-related functions to new `rules.ts` file
- moved Provider-related functions back to `Provider.ts` file (only place they are used)
- `index.ts` now only holds generic / primitive utility functions
This should make it easier to contribute as it's easier to grok what's there.
> refactor: clean up utils index

- docs/api/rules.md
🔎 __Overview__
Noticed there were a couple of typos at the top of the `rules.md` file.
This PR adds the corrections.
Before:
`VeeValidate default bundle do no include any of these rules, you can import them indivdually:`
After:
`VeeValidate default bundle does not include any of these rules, you can import them individually:`
N/A
> add typo fix on rules markdown

- docs/guide/advanced-validation.md
🔎 __Overview__
This PR is about a potential fix for the related issue #2358. There was a bug when visiting the [advanced validation](https://logaretm.github.io/vee-validate/guide/advanced-validation.html#dynamic-messages) page for the cross-field validation part. If we start from the accessibility page and then scroll to the bottom by clicking the next section (do this until you reach the page related to the problem), the validation system will not work anymore and the 'password' and 'confirmation' fields will never correspond.
__My solution__
I have changed the rules for the _StyledProvider_ related to the **password** field. First, I pass an object instead of a string, and then, in the **password** field, I directly put the value of the **confirmation** field (v-model = _confirm_). …
> fix(docs): validation observer for advanced validation

- locale/ja.json
🔎 __Overview__
This PR added the integer message to ja local because it is missing.
> fix: added the integer message to ja local

- src/components/Provider.ts
- src/index.full.ts
- src/index.ts
- src/localeChanged.ts
- src/localize.ts
- src/types.ts
- src/validate.ts
- tests/localize.spec.js
🔎 __Overview__
Since `v3` has shipped with changes to the locale system being more tool agnostic, the developers have been missing the feature to re-render validation messages after locale changes. This PR introduces a `localeChanged` function which should help them trigger updates throughout their application.
Proposed API:
```js
import { localeChanged } from 'vee-validate';
// call it whenever you need the messages to re-render.
localeChanged();
// VueI18n example
this.$i18n,locale = 'ar';
localeChanged();
```
Furthermore, the `localize` function already handles that for you if you use the shipped minimal i18n feature:
```js
import { localize } from 'vee-validate';
// messages will re-render automatically.
localize('ar');
```
closes #2074
> feat: added localeChanged helper to force providers to re-validate

- docs/guide/rules.md
🔎 __Overview__
This PR adds docs.
It fixes TS(7053) error.
`Element implicitly has an 'any' type because expression of type 'string' can't be used to index type 'typeof import(".../node_modules/vee-validate/dist/rules")'. No index signature with a parameter of type 'string' was found on type 'typeof import(".../node_modules/vee-validate/dist/rules")'.ts(7053)`
**[AS-IS]**
**[TO-BE]**
``` ts
import { extend } from "vee-validate";
import * as rules from "vee-validate/dist/rules";
for (let [rule, validation] of Object.entries(rules)) {
extend(rule, {
...validation
});
}
```
> docs: added Installing All Rules with typescript

- src/components/Observer.ts
Flags weren't initialized at all in the observer, which was reliant on the watcher being run at least once. Which won't happen if the observer is empty.
closes #2527
> fix: initialize observer flags properly 

- locale/it.json
🔎 __Overview__
(Locale):
> This PR changes the it messages style because the confirmation message shows up the hidden password
> Correction in the translation of "confirmed" rule for it

- src/components/Observer.ts
- tests/providers/observer.js
This PR introduces a different strategy to handle nested observers which have been very confusing. The observers' errors were also nested, but this PR merges errors that make the structure predictable. Which allows us to tackle #1923 and #2484 
closes #2528
> feat: nest nested observer errors instead of nesting

- docs/guide/localization.md
- src/extend.ts
- src/localize.ts
> fix: internal dictionary not resolving message to newly registered rules

- docs/guide/rules.md
Anchors are lowercased, this one has an uppercase
> Fix broken anchor on doc

- tests/providers/observer.js
🔎 __Overview__
Refactor the observer tests to use `jest.useFakeTimers()` instead of really waiting 50ms.
> refactor(tests): use jest fake timers

- docs/guide/getting-started.md
🔎 __Overview__
`npm install vee-validate` gets the latest package which is `3.*` and this doc is for vee-validate 2.
> Change package version based on the doc

- docs/guide/basics.md
🔎 __Overview__
This PR adds in the docs missing information about validation without using `v-model`.
closes #2615
> docs: added info about validation without v-model

- docs/api/validator.md
Minor fix for the V2 documentation.
(Sigh... eventually I'll get to switch to V3!)
🔎 __Overview__
This PR corrects the link to v2's FieldBag.js in the V2 docs.
See [this page](http://vee-validate.logaretm.com/v2/api/validator.html#api) and click on `FieldBag` to observe the broken link.
> Fix v2 docs link to fieldBag

- docs/guide/basics.md
The example in "Messages as Functions" results in the message "ReferenceError: min is not defined".
🔎 __Overview__
Ex (Feat):
Ex (Locale):
```js
// some code
```
> Fix example in "Messages as Functions"

- src/localize.ts
- tests/localize.spec.js
🔎 __Overview__
This PR fixes the template of default error message. Uses `{_field_}` instead of "invalid" param `{field}` name 
> closes #2641
> Use field name in template for default error message

- docs/guide/rules.md
here is how to import some common rules like `required` and `min` should be here is how to import some common rules like `required` and `email`
🔎 __Overview__
this PR correct a typo in the rule name been imported in de code sample, in code you're importing required and email, but in the previous paragraph you're saying that the rules beeing imported are required and min rules
> rule's name typo

- docs/advanced/testing.md
🔎 __Overview__
Looks like there was a typo here, and I don't think the directory appreciates being called "rood" :) 
I looked around at docs for a while and tried to make sure that `roodDir` isn't actually a thing, and it does look like it was just a simple typo. Let me know if I missed something here
> Fix typo in "Testing Caveats" doc

- docs/guide/localization.md
I stumbled above this origin example and used it with vue-i18n plugin. I was wondering why the localization worked almost, but the field didn't get translated. In the other sandbox for LingUI i found what i was looking for and added this line to the defaultMessage function for the fields translation. It think i would help others.
🔎 __Overview__
Ex (Feat):
> This PR improves the documentation.
Changed this: 
```js
configure({
// this will be used to generate messages.
defaultMessage: (_, values) => i18n.t(`validations.${values._rule_}`, values)
});
```
to this
```js
configure({
// this will be used to generate messages.
defaultMessage: (field, values) => {
values._field_ = …
```
> Default with field translation?

- docs/guide/basics.md
> This PR improves the docs by adding a missing word on the CDN sentence.
you may to use the kebab --> you may *have* to use the `kebab
> Doc : Added missing word on CDN paragraph

- docs/guide/forms.md
Does `hint` actually exist? Either way, it's broken currently. It also seems like this was supposed to be a tip.
Relevant page link:
https://logaretm.github.io/vee-validate/guide/forms.html#resetting-forms
> Doc: Use tip instead of hint?

- docs/.vuepress/config.js
- docs/advanced/model-less-validation.md
- docs/guide/basics.md
- docs/guide/localization.md
- docs/migration.md
- src/components/Provider.ts
- src/utils/vnode.ts
This PR adds a limit to the `ValidationProvider` tree traversal to only one input `VNode` which solves infinite loop issues where multiple providers could exist within one another and other possible edge cases with multiple `v-models`.
Overall this improves performance as well since the traversal doesn't navigate the entire tree but should be minimal as it's unlikely that large trees would exist in `ValidationProvider` slot.
This would make `Radio` inputs harder to validate as they will no longer be treated as the same input, the recommended workaround is to wrap radio inputs in a `RadioGroup` component. I will investigate better workarounds in the future.
closes #2638
closes #2470
> fix: limit v-model nodes to only one node

- docs/guide/rules.md
🔎 __Overview__
This PR adds the documentation of `excluded` rule and fixes the documentation of `oneOf` rule to be consistent.
> Add missing documentation of excluded rule

- locale/ja.json
🔎 __Overview__
This PR added the is_not message to ja local because it is missing.
> fix: added the is_not message to ja local

- packages/docs/content/api/form.md
🔎 __Overview__
A tiny fix in the Form docs.
> docs: remove duplicated isSubmitting option

- packages/docs/content/api/error-message.md
- packages/docs/content/api/form.md
🔎 __Overview__
The `Form` and `ErrorMessage` components docs currently contain typos in their titles.
> docs: fix titles

- docs/advanced/testing.md
This PR imporoves the doc, especially the testing part. I removed sync mode from vueTestUtils, since [it has been removed](https://github.com/vuejs/vue-test-utils/issues/1137).
I also add the import of flushPromises(). It took quite some time to find out that it was an external package.
The only way I got my tests working is by adding `beforeEach(() => jest.useFakeTimers())` at the top of my tests. `jest.useFakeTimers()` was not sufficient. But I think it's more related to Jest, or my misknowledge of Jest, so I didn't change this part. But I'm willing to if you think it's worth.
> docs(testing): removed sync mode from vueTestUtils

- docs/api/validation-provider.md
🔎 __Overview__
The documentation entry for [`ValidationProvider.syncValue()`](https://logaretm.github.io/vee-validate/advanced/model-less-validation.html#value-synchronization) was is missing from the `ValidationProvider` methods section.
> docs: add ValidationProvider.syncValue()

- docs/guide/localization.md
🔎  __Overview__
Since the structure of `locale/<anything>.json` is
```json
{
"code":  "en",
"messages": {
"required": "The {_field_} field is required"
}
}
```
and on the example we instantiate VueI18n this way
```javascript
const i18n = new VueI18n({
locale: 'en',
en: {
validations: validationMessages
}
});
```
I think the correct parameter for translation function is `$t('validations.messages.required', values)`
Nothing
> docs: Update Parameter for VueI18n Translation Function Parameter

- src/rules/length.ts
- tests/modes.spec.js
- tests/providers/provider.js
- tests/rules/length.js
🔎 __Overview__
This PR counts the length of strings as chars not as bytes.
Some unrelated tests failed. I tried to fix them also.
```js
'𥑮'.length === 2  // true 👎 
Array.from('𥑮').lengts === 1 // true 👍 
```
> closes # {2876}
> fix: unicode characters not counted correctly in length rule

- packages/core/src/useForm.ts
- packages/core/tests/Form.spec.ts
_values is not an array but object.
change line _values[fieldName].splice(valueIdx, 1);
into delete _values[fieldName] in unRegister function
🔎 Overview
When submitting a Form with a Field as radio the following error occus:
Uncaught (in promise) TypeError: _values[fieldName].splice is not a function at Object.unregister (vee-validate.esm.js:777) at vee-validate.esm.js:421 at callWithErrorHandling (vue.js:1257) at callWithAsyncErrorHandling (vue.js:1266) at Array.hook.__weh.hook.__weh (vue.js:3451) at invokeArrayFns (vue.js:263) at unmountComponent (vue.js:5884) at unmount (vue.js:5798) at unmountChildren (vue.js:5930) at unmount (vue.js:5813)
fixes #2883
> Fix issue with Form and Field as radio

- packages/core/src/Form.ts
- packages/core/src/types.ts
- packages/core/src/useField.ts
- packages/core/src/useForm.ts
- packages/core/src/utils/assertions.ts
- packages/core/src/utils/common.ts
- packages/core/src/utils/consts.ts
- packages/core/src/utils/index.ts
- packages/core/tests/Field.spec.ts
- packages/core/tests/Form.spec.ts
- packages/docs/components/DocMenu.vue
- packages/docs/content/guide/nested-objects-and-arrays.md
🔎 __Overview__
This PR adds the ability to structure form fields into nested objects #2890 
Todo:
Example:
```vue
<Form @submit="onSubmit">
<Field name="user.name" rules="required"  />
<Field name="user.password" type="password" rules="required"  />
<Field name="user.social[0]" type="url" rules="required"  />
<Field name="user.social[1]" type="url" rules="required"  />
<button id="submit">Submit</button>
</Form>
```
Submitting the above form will result in the following `values`:
```js
{
user: {
name: "John Doe",
password: "123456",
social: [
"link1",
"link2"
]
}
}
```
closes #2890
> feat: nested objects/arrays

- packages/core/src/useField.ts
- packages/core/tests/Form.spec.ts
🔎 __Overview__
The initialValues are not taken into account for radio and also checkbox I think.
I proposed a fix + extra test case
> closes #2906
> fix(core): in case of radio or checkbox explicitly set initialValue

- packages/core/src/Field.ts
- packages/core/src/config.ts
- packages/core/src/useField.ts
- packages/core/tests/Field.spec.ts
- packages/docs/content/api/configuration.md
- packages/docs/content/guide/validation.md
🔎 __Overview__
In vee-validate v3 we had the `interaction` modes idea that allowed customizing validation events dynamically. This was an overkill because almost always the events are the same `input`, `change` or `blur`.
Instead in v4 this is a more strict version of that, you can only choose to validate on one of those events:
- `change`
- `input`
- `blur`
- `update:modelValue`
By default the new validation events are `change`, `blur` and `update:modelUpdate`, this might be a breaking change because vee-validate will no longer validate on input by default.
Some research showed that almost always people used the `lazy` or `eager` modes, but not the `aggressive` mode which was the default one for `vee-validate@3`.
> feat: validation triggers

- docs/content/api/field.md
- docs/content/api/use-field.md
- docs/content/guide/i18n.md
- docs/content/guide/validation.md
- packages/core/src/Field.ts
- packages/core/src/useField.ts
- packages/core/src/validate.ts
- packages/core/tests/Field.spec.ts
This PR adds a `label` prop on the `Field` component to allow renaming fields.
closes #2831
> feat: field labels

- docs/content/api/field.md
- docs/content/api/form.md
- docs/content/api/use-field.md
- docs/content/guide/handling-forms.md
- docs/content/guide/validation.md
- packages/core/src/Field.ts
- packages/core/src/Form.ts
- packages/core/src/useField.ts
- packages/core/src/useForm.ts
- packages/core/tests/Field.spec.ts
- packages/core/tests/Form.spec.ts
- packages/i18n/tests/index.spec.ts
- rename the `immediate` prop on `useField` function and `Field` component to `validateOnMount`
- add `validateOnMount` to the `Form` component
> feat: added `validateOnMount` prop to `Field` and `Form` components

- packages/core/src/Field.ts
- packages/core/src/useField.ts
- packages/core/src/useForm.ts
- packages/core/tests/useField.spec.ts
This PR introduces a simple re-render lock in the `<Field />` component to prevent model updates if the most recent update was caused by a value change
closes #2941
> fix: prevent recursive re-render model update

- docs/content/guide/handling-forms.md
- packages/core/src/Form.ts
- packages/core/src/useField.ts
- packages/core/src/useForm.ts
- packages/core/src/utils/common.ts
- packages/core/tests/Form.spec.ts
🔎 __Overview__
The `initialValues` on `Form` and `useForm` is not reactive, which limits it's usefulness. For example, fetching data from an API then populating the form won't be possible.
This PR allows the `initialValues` prop to be reactive and will only update the `pristine` fields (non-dirty) to avoid resetting the values each time.
> feat: reactive initial form values

- docs/content/api/use-form.md
- docs/content/guide/handling-forms.md
- packages/core/src/Form.ts
- packages/core/src/types.ts
- packages/core/src/useForm.ts
- packages/core/tests/Form.spec.ts
- packages/core/tests/useForm.spec.ts
🔎 __Overview__
Currently there is no way to set the fields errors without using `useField`.
This PR adds two new functions:
- `setFieldError`: sets a single field error message
- `setErrors`: sets error messages for multiple fields
Both of these methods are available on the scoped slot props of the `<Form />` component and return value of `useForm` and in the submission callback and as instance methods (with template `$refs`)
> chore: added docs deploy script

- docs/content/api/form.md
- docs/content/api/use-form.md
- docs/content/guide/handling-forms.md
- packages/core/src/Form.ts
- packages/core/src/types.ts
- packages/core/src/useForm.ts
- packages/core/tests/Form.spec.ts
🔎 __Overview__
Currently there is no way to update fields values without using `useField` or `v-model`, the initial values don't cut it as they only modify the pristine fields.
This PR adds:
- setFieldValue: updates a single field's value
- setValues: updates the specified fields' values
> feat: form and fields values setters

- packages/core/src/types.ts
- packages/core/src/useField.ts
- packages/core/src/useForm.ts
- packages/core/src/utils/common.ts
- packages/core/tests/Field.spec.ts
- packages/core/tests/Form.spec.ts
🔎 __Overview__
The meta tags API wasn't updated or revised since v2 releases. Here are the various problems I see with it:
- Redundant opposite flags (vaid x invalid, dirty x pristine, touched x untouched)
- Confusing flags `valid` vs `passed` and `invalid` vs `failed`
- Some flags are impossible to be accurate (`changed`) which will make immutable fields with arrays or objects as values impossible to be accurate.
- Possibly remove the `valid` flag, you can always check error messages as an alternative
The new API removes a bunch of flags: `untouched`, `pristine`, `invalid`, `passed`, `failed`, `validated`, and `changed`. All of these flags information can be inferred from their opposite one and a combination of one or more.
For example, the `passed` flag is just `dirty` and `valid`, …
> feat: new meta tags API

- packages/core/src/useForm.ts
🔎 __Overview__
Currently the type of `meta` returned by `useForm` is not accurate.
For example in beta 8, we have:
```typescript
meta: ComputedRef<{
initialValues: Record<string, any>;
}>;
```
This commit should improve the typings to:
```typescript
meta: ComputedRef<{
valid: boolean;
dirty: boolean;
touched: boolean;
pending: boolean;
initialValues: Record<string, any>;
}>;
```
> fix: improve useForm meta types

- docs/content/api/field.md
- docs/content/api/form.md
- docs/content/api/use-field.md
- docs/content/api/use-form.md
- package.json
- packages/core/src/Field.ts
- packages/core/src/Form.ts
- packages/core/src/types.ts
- packages/core/src/useField.ts
- packages/core/src/useForm.ts
- packages/core/tests/Field.spec.ts
- packages/core/tests/Form.spec.ts
- packages/core/tests/useForm.spec.ts
- yarn.lock
🔎 __Overview__
Currently, there is no way to set meta tags safely without affecting the value, the field `meta` is marked as read-only in docs.
This PR adds safe setters that can be used on the field and form levels via either flavors of the library
> feat: meta setters

- docs/api/validation-provider.md
- src/components/Provider.ts
- tests/providers/provider.js
🔎 __Overview__
This PR adds the feature to disable automatic `v-model` detection.
Ignoring the `v-model`ed element and using `validate()` to validate the second input's value instead.
```html
<ValidationProvider v-slot="{ validate }" :detectInput="false">
<input v-model="field" type="text"> 
<input type="text" @change="validate($event.target.value)">
```
> closes #2979
> feat: added detectInput

- src/components/Observer.ts
Currently this does not work: 
`<ValidationObserver v-slot="{ validateWithInfo }">`
and instead we can only use the derived version:
`<ValidationObserver v-slot="{ validate }">`
which doesn't provide the error information.  This PR exposes that more powerful validation function.
> Expose validateWithInfo as Observer slot-prop

- docs/content/api/form.md
- docs/content/api/use-form.md
- docs/content/guide/handling-forms.md
- packages/core/src/Form.ts
- packages/core/src/useForm.ts
- packages/core/tests/Form.spec.ts
- packages/core/tests/helpers/index.ts
🔎 __Overview__
This PR adds `initalErrors` prop that prefills form's errors and updates their validation state.
This is useful for Non-Nodejs SSR like Laravel to easily add error messages to their forms after flashing them to session from the previous response.
> feat: add `initialErrors` prop

- docs/content/api/form.md
- docs/content/api/use-form.md
- packages/core/src/Form.ts
- packages/core/src/useForm.ts
- packages/core/tests/Form.spec.ts
🔎 __Overview__
The recent addition of `initialErrors` limits "show errors on touched" as while the errors are present they won't be displayed, even with `validateOnMount` enabled. So we need a way to set initial `touched` and `dirty` meta flags as well. 
This PR adds `initialDirty` and `initialTouched` to the `<Form />` and `useForm()` to do just that.
> feat: initial form meta

- src/components/Observer.ts
- tests/providers/observer.js
🔎 __Overview__
Right now the `disabled` prop in `ValidationObserver` is not very useful because it only prevents the validation in nested observer when calling `validate()` method on the parent observer. However, it does not prevent the validation when changing providers state which are inside nested observer.
This makes very hard to implement validation for nested forms. In nested forms you often have a situation when you don't want the child form to trigger validation in the parent form.
After this PR nested disabled child observers will not change the state of the parent observer. Also parent observers will not collect errors from nested disabled child observers.
Here is the form which I was using to test the changes.
```vue
<template> …
```
> Ignore nested disabled observers when computing observer state

- docs/guide/testing.md
Hi folks! 😄 Vue Test Utils maintainer here 👋 . Sync mode was finally deprecated and removed, so you can safely remove the tip, too :)
> Remove mention of sync mode from Vue Test Utils

- packages/rules/src/regex.ts
🔎 __Overview__
Regex validator seems to be generating regex formula from the wrong parameter.
new RegExp() receives the input value and not regex formula
> wrong rule applied?

- docs/components/DocMenu.vue
- docs/components/SideMenu.vue
🔎 __Overview__
Fixed scrolling menu in mobile safari.
Ex (Feat):
It is currently impossible to scroll the menu to the end. Adjusted the maximum height of the menu to have a bottom gap. Also add `overscroll-behavior-y` to get rid of the underlying page scroll chaining.
> fix safari sidemenu scroll issue

- docs/content/api/use-form.md
🔎 __Overview__
Fix typo (initialErrors -> initialValues) in Docs.
> fix typo in docs (initialErrors -> initialValues)

- packages/vee-validate/src/Form.ts
- packages/vee-validate/src/types.ts
- packages/vee-validate/src/utils/vnode.ts
🔎 __Overview__
The `Form` component emitting `submit` event with different signature than the default event handlers.
This PR adds `onSubmit` prop and `emits` prop so tools like `volar` and `vue-dx` can pick up the types correctly.
https://github.com/johnsoncodehk/volar/issues/41
closes #3114
> fix: added emits and onSubmit custom prop

- docs/content/api/use-form.md
- docs/content/guide/composition-api.md
- docs/content/guide/handling-forms.md
- docs/content/guide/validation.md
- docs/content/tutorials/best-practices.md
- docs/content/tutorials/dynamic-form-generator.md
- package.json
- packages/vee-validate/src/types.ts
- packages/vee-validate/src/useForm.ts
- packages/vee-validate/tests/Form.spec.ts
- packages/vee-validate/tests/useForm.spec.ts
- yarn.lock
🔎 __Overview__
This drops the usage of outdated `@types/yup` and uses the new internal types. Enhances compatibility between the generic `useForm` and yup's `Schema`
> feat: use internal yup types

- docs/content/api/form.md
- docs/content/api/use-form.md
- packages/vee-validate/src/Form.ts
- packages/vee-validate/src/types.ts
- packages/vee-validate/src/useForm.ts
- packages/vee-validate/tests/useForm.spec.ts
This PR adds a `validateField` method on both `Form` component and `useForm` function, this allows validating a single field.
```js
import { useForm } from 'vee-validate';
const { validateField } = useForm();
const { valid, errors } = await validateField('email');
```
```vue
<Form v-slot="{ validateField }">
<button @click="validateField('email')">Validate Email</button>
</Form>
```
As mentioned in #3131
> feat: added validate field function to form and useForm

- packages/vee-validate/src/Field.ts
https://v3.vuejs.org/api/options-data.html#emits
I'm currently getting a warning `Component emitted event "update:modelValue" but it is neither declared in the emits option nor as an "onUpdate:modelValue" prop.` without this.
> Feat: Add emits option to Field component

- docs/components/DocMenu.vue
- docs/content/guide/components/validation.md
- docs/content/guide/composition-api/validation.md
- docs/content/integrations/3rd-party-integrations.md
- docs/content/integrations/zod-schema-validation.md
- packages/zod/README.md
- packages/zod/package.json
- packages/zod/src/index.ts
- packages/zod/tests/zod.spec.ts
- yarn.lock
🔎 __Overview__
Add support for zod schemas by adding a new "resolver" package that converts them to `yup`-like schemas.
```js
import { toFormValidator } from '@vee-validate/zod';
import * as zod from 'zod';
import { toFieldValidator } from '@vee-validate/zod';
// Field schema to be used with `Field.rules` prop or `useField`
const fieldSchema = toFieldValidator(zod.string().nonempty(REQUIRED_MSG).min(8, MIN_MSG));
// Field schema to be used with as form validation schema
const schema = toFormValidator(
zod
.object({
password: zod.string(),
confirmation: zod.string(),
})
.refine(data => data.confirmation === data.password, {
message: CONFIRM_MSG,
path: ['confirmation'],
})
);
```
closes #3160
> feat: initial zod support

- README.md
🔎 __Overview__
This PR fixes syntax error in the example of declarative components.
> chore: fix syntax error in readme

- packages/i18n/src/locale/lt.json
🔎 __Overview__
This PR fixes the lt locale translation.
> Fixed mistype in digits translation for LT locale #3209

- packages/vee-validate/src/index.ts
🔎 __Overview__
If i need to pass `form` variable to the nested component, i want to define prop type, and for that i we need to export `PublicFormContext`
i've checked it's working.
**App.vue**:
```vue
<template>
<TestForm :form="form" />
</template>
<script lang="ts">
export default defineComponent({
setup() {
const form = useForm<SomeInterface>(); // form: PublicFormContext<SomeInterface>
return {
form,
};
},
});
</script>
```
**TestForm.vue**:
```vue
<script lang="ts">
import '...';
// I need this
import { PublicFormContext } from 'vee-validate';
export default defineComponent({
props: {
form: {
type: Object as PropType<PublicFormContext<SomeInterface>>, // to use here
},
},
});
</script>
```
> Export PublicFormContext interface

- packages/shared/utils.ts
- packages/vee-validate/src/Field.ts
- packages/vee-validate/tests/Field.spec.ts
🔎 __Overview__
As we've discussed [here](https://github.com/logaretm/vee-validate/issues/3230). The `v-model.number` modifier triggers the validation on every type regardless of the validation triggers settings. It only affects `number` modifier, `trim` modifier works just fine.
This PR adds the support for `v-model.number` modifier.
Closes #3230
> feat: support `v-model.number`

- docs/content/guide/global-validators.md
- packages/i18n/src/locale/en.json
- packages/i18n/src/locale/pt_BR.json
- packages/i18n/src/locale/pt_PT.json
- packages/rules/src/url.ts
- packages/rules/tests/url.spec.ts
🔎 __Overview__
The `url` validator is really common validator which makes sense to bring it back, as discussed [here](https://github.com/logaretm/vee-validate/issues/3104).
Even though the issue suggests the usage of [RFC 3986](https://www.ietf.org/rfc/rfc3986.txt) regexp. I believe using `URL` constructor will be more aligned with HTML5 specification [[1]](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/url#basic_validation) [[2]](https://url.spec.whatwg.org/#goals)
Usage:
```html
<Field name="url" type="url" rules="url" />
<Field name="secure_url" type="url" rules="{ url: /https:\/\/.*/ }" />
```
closes #3104
> feat(rules): add url validator

- docs/content/guide/components/validation.md
- docs/content/guide/composition-api/validation.md
- packages/vee-validate/src/Form.ts
- packages/vee-validate/src/types.ts
- packages/vee-validate/src/useField.ts
- packages/vee-validate/src/useForm.ts
- packages/vee-validate/tests/Form.spec.ts
🔎 __Overview__
Adds support for reactive form schemas for the `<Form />` and `useForm`
It allows using `computed` to create reactive schema objects
```js
import * as yup from 'yup';
import { computed, ref } from 'vue';
import { useForm } from 'vee-validate';
const accepted = ref(['1', '2', '3']);
const schema = computed(() => {
return yup.object({
field: yup.string().oneOf(accepted.value);
})
});
useForm({
validationSchema: schema
});
```
closes #3235
> feat: added support for reactive schemas

- docs/concepts/injections.md
- docs/guide/localization.md
- docs/guide/messages.md
🔎 __Overview__
This PR provides a minor grammar fix for V2, changing three instances of possessive "its" from "it's" to "its".  
That's all.  Small potatoes.  My mom was a teacher, what can I say.
N/A
No issues affected.
> grammar fix: it's -> its

- packages/vee-validate/src/types.ts
- packages/vee-validate/src/useField.ts
- packages/vee-validate/src/useForm.ts
- packages/vee-validate/tests/Field.spec.ts
- packages/vee-validate/tests/useField.spec.ts
Corrects the initial value state management which would be a wrapped ref sometimes causing the `dirty` flag to have a wrong value after reset
closes #3272
> fix: unwrap initial value with useField.resetField fixes #3272

- docs/content/guide/global-validators.md
Wrong const name is used in doc.
> Fix example register for all rules

- docs/content/guide/components/handling-forms.md
- docs/content/guide/composition-api/handling-forms.md
- packages/vee-validate/src/useForm.ts
- packages/vee-validate/tests/Form.spec.ts
🔎 __Overview__
This PR adds minor enhancements to `touch` all fields when submitting the form, this consideration allows using `meta.touched` to reliably show error messages for some use-cases.
> feat: touch all fields on submit

- packages/vee-validate/src/Field.ts
- packages/vee-validate/src/symbols.ts
- packages/vee-validate/src/utils/assertions.ts
As reported in #3294 the new behavior of prop keys always present causes issues with checkboxes and initial value detection, this is caused by the reliance on detecting if a user didn't pass a `model-value` prop.
This PR mitigates this by introducing a unique symbol value as a default to deter when the user didn't pass a model value.
> fix: added a symbol to detect non passed props with Vue 3.1.x

- docs/content/api/use-field.md
- docs/content/examples/custom-checkboxes.md
- packages/vee-validate/src/Field.ts
- packages/vee-validate/src/types.ts
- packages/vee-validate/src/useField.ts
- packages/vee-validate/src/useForm.ts
This PR renames the `valueProp` option used by `useField` to `checkedValue` since this is its only valid use.
This can be a breaking change but at the moment it accounts for both `valueProp` and `checkedValue`, so it's backward compatible.
> chore: rename the value prop to checkedValue

- docs/content/api/field.md
- docs/content/api/use-field.md
- docs/content/guide/components/validation.md
- docs/content/guide/composition-api/validation.md
- packages/vee-validate/src/Field.ts
- packages/vee-validate/src/types.ts
- packages/vee-validate/src/useField.ts
This fixes the cases where the input has disabled the `validateOnChange` while relying on it to update the value, like `checkbox` components/inputs 
This deprecates the `handleInput` and instead introduces an optional argument called `shouldValidate` on the `handleChange` function.
```js
const { handleChange } = useField('field');
handleChange('new value');
handleChange('new value 2', false); 
```
closes #3298
> fix: deprecate handleInput and use handleChange for both events

- src/components/Provider.ts
- tests/providers/provider.js
🔎 __Overview__
This PR fixes the bug with provider changed flag.
It now works with object and array values.
I use the pre-existing `isEqual` function instead of a simple equality operator.
(and add tests :wink: )
closes #3300
> fix(provider): changed flag computation

- packages/vee-validate/src/useForm.ts
- packages/vee-validate/tests/Form.spec.ts
This PR fixes #3384 and https://github.com/formvuelate/formvuelate/issues/210
> fix: clean error message for singular fields after unmount

- src/rules/alpha_helper.ts
🔎 __Overview__
Hebrew characters are not being validated, even though error messages are correctly shown
This PR adds the hebrew regex
> add hebrew regex validations

- packages/i18n/package.json
- packages/rules/package.json
- packages/vee-validate/package.json
- packages/zod/package.json
> If the package.json for your package is not in the root directory (for
example if it is part of a monorepo), you can specify the directory in
which it lives:
> ```json
> "repository": {
>   "type" : "git",
>   "url" : "https://github.com/facebook/react.git",
>   "directory": "packages/react-dom"
> }
> ```
> — https://docs.npmjs.com/cli/v6/configuring-npm/package-json#repository
I use a lot https://njt.vercel.app/ to jump to different packages information,
and with this PR we can know exactly what package in what folder lives
Made the changes with a script to make it easier 🙂
https://gist.github.com/iamandrewluca/5cc85b56a595056f0099d04ed6dd8a79
> chore: add repository for all packages.json

- packages/vee-validate/src/types.ts
> `handleReset: () => void`
>
> Similar to `resetField` but it doesn't accept any arguments and can be safely used as an event handler. The values won't be validated after reset.
> ```ts
> const { handleReset } = useField('field', value => !!value);
>
> // reset the field validation state and its initial value
> handleReset();
> ```
>
> https://vee-validate.logaretm.com/v4/api/use-field#composable-api
> fix(types): remove arguments of PrivateFieldContext.handleReset

- src/rules/double.ts
- tests/rules/double.js
🔎 Overview
Change Double Rule
I added an condition to determine if the value is an integer or not. Because when you use the double rule in V3, you must put .0 after an integer. (in my case the value can be an integer or a double). For my case SQL server doesn't register float like 0.0 and just save 0 instead . But when I edit the value in my website, i need to put .0 (because SQL retrieve an integer) on each double value where it's an integer in DB.
(good for test this time^^)
🤓 Code snippets/examples (if applicable)
No code to test, use it as it should, it now validate if the value is an integer.
✔ Issues affected
closes #3207
> fix: update Double rules to accept integer values

- packages/vee-validate/src/types.ts
Doing a search for `KnownKeys` in the entire project, gives 0 results.
> refactor(vee-validate): remove unused KnownKeys type

- packages/i18n/src/index.ts
- packages/i18n/src/locale/de.json
- packages/i18n/src/locale/en.json
- packages/i18n/src/locale/fr.json
- packages/i18n/src/locale/nl.json
- packages/i18n/tests/index.spec.ts
🔎 __Overview__
Added a feature to add a language specific default. 
Current behaviour was always an English message. 
Logic: 
if for the specific language a _default is set, then show that default. 
If there is no default set, the fallback-english is used.
> feat: added language specific default

- docs/content/tutorials/basics.md
This [documentation page](https://vee-validate.logaretm.com/v4/tutorials/basics) is for v4.x (Vue3), it should be using `vee-validate@next` instead of `vee-validate`.
🔎 __Overview__
Updated `docs/content/tutorials/basics.md`
Original:
```sh
yarn add vee-validate
npm install vee-validate
```
To:
```sh
yarn add vee-validate@next
npm install vee-validate@next --save
```
> [v4]Minor documentation error: it should be vee-validate@next for v4.x (Vue 3)

- packages/i18n/src/locale/et.json
🔎 __Overview__
Basically the same as #3579 but for v4. In addition I also added messages for `default` and `url`. It should cover all available rules now.
> fix: improved et locale

- docs/.vuepress/theme/layouts/Layout.vue
🔎 __Overview__
There was a simple css bug in [v2 docs](https://vee-validate.logaretm.com/v2/guide/). Padding wasn't working. We at the company were using the v2 and it was getting more of a issue by time. Heading was hidden behind top navs.
🤓 __Just added important to one of the css rule__
```js
.theme-default-content.content__default
padding-top: calc(2rem + 50px) !important
```
> Make content padding important

- packages/vee-validate/src/types.ts
- packages/vee-validate/src/useFieldArray.ts
- packages/vee-validate/tests/FieldArray.spec.ts
- packages/vee-validate/tests/useFieldArray.spec.ts
This PR implements an enhancement for the `FieldArray` or `useFieldArray` where it wasn't possible to use `v-model` with it to mutate the iterable value directly.
The motivation for that design is to force the lib user to go through the API, however, it doesn't seem necessary to have this restriction as `v-model` is an initiative way to mutate such values.
This was mentioned in #3617 discussion
> feat(4.6): Allow mutating field array iterable's value property

- docs/api/validation-provider.md
Make it clear that vid's must be unique across single ValidationObserver instance.
🔎 __Overview__
```js
// some code
```
> Clarify vid prop.

- docs/content/guide/global-validators.md
This PR fixes inconsistency in custom validator names and their usages.
> Fixed typos in 'Global Validators' guide section

- packages/vee-validate/src/Field.ts
- packages/vee-validate/src/Form.ts
- packages/vee-validate/src/types.ts
- packages/vee-validate/src/useField.ts
- packages/vee-validate/src/useForm.ts
- packages/vee-validate/tests/Form.spec.ts
🔎 __Overview__
This PR adds a configuration to change the automatic behavior of unsetting field values when the components are unmounted.
The configuration is available on both the form level and the field level.
```js
useField('name', undefined, { keepValueOnUnmount: true });
useForm({ keepValuesOnUnmount: true });
```
```vue
<Field name="fieldName" keep-value />
<Form keep-values>
....
</Form>
```
closes #3795
closes #3607
> feat: added unsetValueOnUnmount config

- packages/vee-validate/src/types.ts
- packages/vee-validate/src/useFieldArray.ts
- packages/vee-validate/src/useForm.ts
- packages/vee-validate/tests/FieldArray.spec.ts
- packages/vee-validate/tests/useFieldArray.spec.ts
🔎 __Overview__
This PR changes how field arrays are registered within forms to allow their instances to be re-used. If the same array path is used for multiple calls of `useFieldArray` or `FieldArray` component then these calls will return the same instance.
This makes the field array state can be used and manipulated from multiple places at once.
closes #3809
> Feat: duplicate calls to useFieldArray with the same path will yield the same API instance

- packages/vee-validate/src/types.ts
- packages/vee-validate/src/useField.ts
- packages/vee-validate/src/useForm.ts
- packages/vee-validate/src/validate.ts
- packages/zod/src/index.ts
- yarn.lock
🔎 __Overview__
This removes `yup` from TS dependencies which causes TS errors for projects not having `yup` installed in their `package.json`.
Closes #3315
> feat: Remove yup type dependency

- packages/vee-validate/src/Field.ts
- packages/vee-validate/src/useField.ts
- packages/vee-validate/src/utils/common.ts
- packages/vee-validate/tests/FieldArray.spec.ts
- packages/vee-validate/tests/useField.spec.ts
This PR adds a new capability to `useField` to allow it to automatically sync the `v-model` directive when it is used on the component that has called it.
This was a common question and issue where multiple people found syncing the `modelValue` prop themselves annoying.
I think this is a nice addition that is relatively safe to introduce into `useField` at this stage.
`useField` will now automatically make the component emit `update:modelValue` and listen to `props.modelValue` changes and sync it with the `value` property. It will also take into account the model modifiers like `v-model.number`.
For custom models names, you can control what the prop/event names are called with `modelPropName` option:
```js
// component will now emit `update:custom` and sync `custom` prop value with the …
```
> feat: Sync useField with component v-model

- docs/content/tutorials/basics.md
I found that https://vee-validate.logaretm.com/v4/guide doesn't have content.
I am not sure if I edit it correctly.
> fix a link on doc

- packages/vee-validate/src/useForm.ts
- packages/vee-validate/tests/FieldArray.spec.ts
This was a tough balancing act, it might cause some issues for some people but I believe the behavior here makes sense.
With this PR fields will no longer be able to force their initial value if the form was provided one. This ensures the original initial values remain unchanged when fields are mounted. This was apparent with `FieldArray`  in #3874 
fixes #3874
> FIX: update field initial value if form has no provided one closes #3874

- packages/vee-validate/src/useField.ts
- packages/vee-validate/src/utils/common.ts
- packages/vee-validate/tests/Form.spec.ts
It fixes an issue where checkboxes have a checked object value by doing a deep equality check instead of simple equality checks.
closes #3883
> Fix: use deep quality check for checkbox values  #3883

- docs/content/guide/composition-api/nested-objects-and-arrays.md
🔎 __Overview__
This PR is for fixing typo in document description.
In `useForm` the correct key of the option is `keepValuesOnUnmount` instead of `keepValueOnUnmount`.
> Typo in `keepValuesOnUnmount` in useForm()

- packages/vee-validate/src/useField.ts
- packages/vee-validate/src/useForm.ts
- packages/vee-validate/src/utils/common.ts
- packages/vee-validate/tests/useField.spec.ts
- packages/vee-validate/tests/useForm.spec.ts
Fixes when an async validation concludes after subsequent validation runs. closes #3906
> fix: handle validation races for async validations

- docs/src/pages/guide/components/validation.mdx
This PR fix mismatch function name in components validation page.
Page: https://vee-validate.logaretm.com/v4/guide/components/validation/
Heading: Field-level Validation
changed "required" to "isRequired"
🔎 __Overview__
```js
<template>
<Form>
<Field name="field" :rules="isRequired" />
<ErrorMessage name="field" />
</Form>
</template>
<script setup>
import { Field, Form, ErrorMessage } from 'vee-validate';
function required(value) {
if (value && value.trim()) {
return true;
}
return 'This is required';
}
</script>
```
changed to 
```js
<template>
<Form>
<Field name="field" :rules="isRequired" />
<ErrorMessage name="field" />
</Form>
</template>
<script setup>
import { Field, Form, ErrorMessage } from 'vee-validate';
function isRequired(value) { …
```
> chore(docs): fix mismatch function name

- packages/vee-validate/src/useField.ts
- packages/vee-validate/tests/useField.spec.ts
By saving a copy of the last value that was watched, we can detect when the `watch` was triggered due to a nested mutation.
Comparing the old value may seem redundant now, but didn't have time to check that.
closes #3926
> fix: handle nested value change validation #3926

- package.json
- packages/vee-validate/src/useField.ts
- packages/vee-validate/src/useFieldState.ts
- packages/vee-validate/src/useForm.ts
- packages/vee-validate/src/utils/assertions.ts
- scripts/config.js
It Fixes file equality comparison which affects model updates, and dirty meta state. By extending `fast-deep-equal` and adding our custom file matching logic.
> fix: extend is equal with file comparison logic #3911

- docs/src/pages/api/use-field-array.mdx
- docs/src/pages/guide/composition-api/nested-objects-and-arrays.mdx
🔎 __Overview__
This PR adds the 'move' function to the array documentation which is currently missing.
> Added array 'move' helper function to the documentation

- docs/src/pages/api/use-field.mdx
Currently, `useField()` accepts an optional `MaybeRef<RuleExpression>`. This updates the docs to match.
> docs: update useField() signature to match implementation

- packages/vee-validate/src/useField.ts
- packages/vee-validate/src/useFieldState.ts
- packages/vee-validate/src/useForm.ts
- packages/vee-validate/tests/useField.spec.ts
Allows passing `form` object created by `useForm` to `useField` for finer control over field-form registration.
closes #3204
> feat: allow passing form control to useField closes #3204

- docs/src/pages/guide/global-validators.mdx
A prefix `v4/` was missing in available rules links
🔎 __Overview__
This PR fixes the broken inline links in the available rules section of global validators.
> Fix broken links for available rules

- docs/src/pages/api/use-field-array.mdx
- docs/src/pages/guide/composition-api/nested-objects-and-arrays.mdx
🔎 __Overview__
This PR makes the examples within the "useFieldArray" documentation a bit more explicit.
Before it wasn't clear to me that you can't call the composable right before using it in a custom function. I think the docs should reflect that.
I also removed the unneccesary 'field' from the examples.
> Update array docs

- packages/vee-validate/src/Field.ts
Since there is no official generic component props support yet, we should mark the field slot prop value to be `any` to avoid errors with `v-model` prop bindings.
closes #3969
> fix: mark slot prop field value as any closes #3969

- packages/vee-validate/src/useFieldArray.ts
- packages/vee-validate/src/utils/common.ts
- packages/vee-validate/tests/useFieldArray.spec.ts
Since `computed` didn't offer deep setter triggers it made mutating a reference type field entry item mutable and didn't trigger validation.
This PR fixes that by introducing a proxy between the form and the field array item that can be deep-watched, so it can trigger validation while disallowing direct mutations over the computed property result.
closes #3968
> fix: correctly mutate deep field array item and trigger validation

- packages/vee-validate/tests/ErrorMessage.spec.ts
- packages/vee-validate/tests/Field.spec.ts
- packages/vee-validate/tests/Form.spec.ts
- packages/zod/tests/zod.spec.ts
A lot of tests still used a redundant prop default value that was needed back in alpha releases but no longer the case. This should slightly reduce the markup of the tests.
> chore: remove redundant as props from early alphas

- packages/rules/src/ext.ts
- packages/rules/tests/ext.spec.ts
🔎 __Overview__
This PR fixes a bug with the ext rule
With the current regex:
```js
// using extensions = ['txt', 'jpg', 'svg']
new RegExp(`.(${extensions.join('|')})$`, 'i');
```
This passes validation on filenames like,
```
filename.etxt
filenamejpg
```
This PR also adds some additional invalid cases to the ext tests.
I discovered this when someone was able to submit a form with a `.epub` which was not in our accept list, however `.pub` was.
> fix: ext rule regex has wildcard when it should be literal period

- docs/src/pages/api/use-field-array.mdx
🔎 __Overview__
fix typo in useFieldArray argument
https://vee-validate.logaretm.com/v4/api/use-field-array#composable-api
> fix: typo in useFieldArray argument

- docs/src/pages/api/use-form.mdx
> fix(docs): typo in use-form.mdx

- packages/vee-validate/src/Form.ts
- packages/vee-validate/src/types.ts
- packages/vee-validate/src/useForm.ts
- packages/vee-validate/tests/Form.spec.ts
🔎 __Overview__
Adds `resetField` on `useForm` and `Form` APIs. It only works for controlled fields at the moment.
closes #4117
> feat(#4117): add resetField on Form/useForm 

- packages/vee-validate/src/Form.ts
- packages/vee-validate/tests/Form.spec.ts
🔎 __Overview__
Exposes a few state getters for `<Form />` state:
- getValues
- getErrors
- getMeta
closes #4006
> feat: expose state getters on the form instance via template refs

- docs/src/pages/integrations/zod-schema-validation.mdx
The latest version of `zod` is `3.20.6`, but the `zod@beta` is [3.20.4-beta.0](https://www.npmjs.com/package/zod/v/3.20.4-beta.0), so we should remove the `beta` flag.
> docs: use the latest zod

- packages/vee-validate/src/index.ts
When I want to expose the remaining FieldContext methods, The ts error appears `Default export of the module has or is using private name 'FieldState'.ts(4082)`
> feat: export type `FieldState`

- .circleci/config.yml
- package.json
- packages/i18n/src/index.ts
- packages/i18n/src/utils.ts
- packages/rules/src/index.ts
- packages/rules/src/toTypedSchema.ts
- packages/rules/tests/toTypedSchema.spec.ts
- packages/shared/types.ts
- packages/shared/utils.ts
- packages/vee-validate/src/index.ts
- packages/vee-validate/src/types.ts
- packages/vee-validate/src/useField.ts
- packages/vee-validate/src/useForm.ts
- packages/vee-validate/src/utils/assertions.ts
- packages/vee-validate/src/validate.ts
- packages/yup/package.json
- packages/yup/src/index.ts
- packages/yup/tests/yup.spec.ts
- packages/zod/package.json
- packages/zod/src/index.ts
- packages/zod/tests/zod.spec.ts
- scripts/build.js
- scripts/config.js
- yarn.lock
This PR augments the support of yup and zod with advanced features to make full use of these libraries capabilities, while also opening the door for 3rd party integrations to have the same features.
This PR introduces the concept of "Input" and "Output" types in a given form schema. For example, consider this yup schema:
```js
yup.object({
email: yup.string().required().email(),
password: yup.string().required()
});
```
Now while this schema validates that a given value has both email and password fields, The user may not enter them. Meaning there is a possibility where `email` and `password` are `undefined` until the user has started changing them. This is an "InputType".
So the schema really makes sure it passes only when both fields satisfy their conditions. TypeScript-wise, it means …
> feat: Better Yup and Zod typing with output types and input inference

- docs/src/pages/guide/composition-api/typed-schema.mdx
This PR fixes some examples in the docs. Currently the docs have examples for using `zod` but all the code examples are using `yup` imports. Note I haven't actually tested the code snippets, but just updated the imports and methods to reflect zod instead of yup.
> Docs Fix: Zod examples should use zod not yup

- packages/rules/src/max.ts
- packages/rules/src/min.ts
- packages/rules/tests/max.spec.ts
- packages/rules/tests/min.spec.ts
🔎 __Overview__
It appears that the current implementation of the String.length method may not accurately reflect the number of characters in a string containing surrogate pairs.
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/length
Specifically, this is the case
https://codepen.io/nao62165/pen/OJBgwjB?editors=1111
With this change, users of surrogate pairs will also receive the expected results.
We hope you will consider this!
The method of using [Intl.Segmenter](https://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Global_Objects/Intl/Segmenter/Segmenter) is also mentioned. Segmenter](), but it is not available in FireFox at this time. Spread syntax has been adopted so that more users can use …
> feat: support consideration for surrogate pairs

- .circleci/config.yml
- package.json
- packages/vee-validate/src/Field.ts
- packages/vee-validate/src/devtools.ts
- packages/vee-validate/src/types/forms.ts
- packages/vee-validate/src/useField.ts
- packages/vee-validate/src/useFieldArray.ts
- packages/vee-validate/src/useFieldState.ts
- packages/vee-validate/src/useForm.ts
- packages/vee-validate/src/useIsFieldDirty.ts
- packages/vee-validate/src/useIsFieldTouched.ts
- packages/vee-validate/src/useIsFieldValid.ts
- packages/vee-validate/src/useValidateField.ts
- packages/vee-validate/src/utils/assertions.ts
- packages/vee-validate/src/utils/common.ts
- packages/vee-validate/tests/FieldArray.spec.ts
- packages/vee-validate/tests/useFieldArray.spec.ts
🔎 __Overview__
Previously, vee-validate used `FieldInstance` to track fields in memory and generate aggregated states based on their paths. This meant unless a field was created with `useField` it won't be tracked which limited a few use cases:
- `useModel` would be unconfigurable and has no meta.
- No concept of virtual fields which has no UI or anything similar.
This refactor redoes that part, the form will create path states and maintain itself. `useField` will mirror the path state with the same `path` as the field `name`. This means a few things will change:
- All fields sharing the same name will have the same meta state, this could be a minor breaking change but I have not seen any cases where you would track the `touched` state of a single checkbox within a group, if anything they …
> refactor: Switch to path-based state tracking

- packages/vee-validate/src/index.ts
- packages/vee-validate/src/types/common.ts
- packages/vee-validate/src/types/forms.ts
- packages/vee-validate/src/useForm.ts
- packages/vee-validate/src/utils/common.ts
- packages/vee-validate/tests/helpers/ModelComp.ts
- packages/vee-validate/tests/useForm.spec.ts
- packages/yup/package.json
- packages/zod/package.json
- pnpm-lock.yaml
🔎 __Overview__
This builds on the refactor of #4238 and adds a new couple of functions:
Generates a bindable object that can be bound with `v-bind` directly to any component given it implements the `v-model` interface.
This means much easier component and 3rd party component integrations without the need to ever wrap it.
Example with Vuetify:
```vue
<script>
const schema = toTypedSchema(yup.object({
email: yup.string().email().required().label('E-mail'),
password: yup.string().min(6).required(),
}));
const { defineComponentBinds } = useForm({
validationSchema: schema
});
const email = defineComponentBinds('email');
const password = defineComponentBinds('password');
</script>
<template>
<v-text-field
v-bind="email"
label="email"
type="email"
/>
<v-text-field
v-bind="password" …
```
> feat: Component and Input binds helpers

- docs/src/pages/api/composition-helpers.mdx
- docs/src/pages/api/form.mdx
- docs/src/pages/api/use-form.mdx
- docs/src/pages/guide/composition-api/api-review.mdx
- packages/vee-validate/src/Form.ts
- packages/vee-validate/src/devtools.ts
- packages/vee-validate/src/index.ts
- packages/vee-validate/src/types/devtools.ts
- packages/vee-validate/src/types/forms.ts
- packages/vee-validate/src/useForm.ts
- packages/vee-validate/src/useIsValidating.ts
- packages/vee-validate/tests/Form.spec.ts
- packages/vee-validate/tests/useIsValidating.spec.ts
🔎 __Overview__
This PR adds the feature that provide `isValidating` state while form's validate method is running.
__Reason__
In some actual code implementations, some object and array fields may be very complicated. So we extract a common components to edit these fields.
For example:
```js
const obj = {
field: {
// nested
}
}
```
The problem is that we want to validate the field `obj.field` through vee-validate, and the internal fields of `obj.field` is validated within common components with custom yup validations.
Common components provide their own validation method (the logic is very complex, and we does't use Field or useField), 
For exapmle:
```js
<template>
<complex-editor 
ref="editorRef" 
v-model="obj.field" 
/>
</template>
<script lang="ts" setup>
const editorRef = ref();  // …
```
> feat: add isValidating state while validate method is running

- packages/vee-validate/src/devtools.ts
🔎 __Overview__
When I upgraded from 4.5 to 4.9, I found that if I use Unicode characters as name, such as emoji, Chinese characters, and use vue devtools, I get window.btoa error
> chore(devtool): add compatibility for UTF character

- packages/vee-validate/src/ErrorMessage.ts
- packages/vee-validate/src/Field.ts
- packages/vee-validate/src/FieldArray.ts
- packages/vee-validate/src/Form.ts
🔎 __Overview__
This PR adds `PURE` tags to the components so that when they are not used, they will be treeshaken by Rollup.
[Rollup REPL](https://rollupjs.org/repl/?version=3.21.7&shareable=JTdCJTIyZXhhbXBsZSUyMiUzQW51bGwlMkMlMjJtb2R1bGVzJTIyJTNBJTVCJTdCJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMCU3QiUyMGRlZmluZUNvbXBvbmVudCUyMCU3RCUyMGZyb20lMjAndnVlJyU1Q24lNUNuY29uc3QlMjBjb21wb25lbnQlMjAlM0QlMjAlMkYqKiUyMCUyM19fUFVSRV9fJTIwKiUyRiUyMGRlZmluZUNvbXBvbmVudCglN0IlNUNuJTIwJTIwc2V0dXAoKSUyMCU3QiU1Q24lMjAlMjAlMjAlMjAlNUNuJTIwJTIwJTdEJTVDbiU3RCklNUNuJTVDbmV4cG9ydCUyMGNvbnN0JTIweWVzJTIwJTNEJTIwdHJ1ZSUzQiUyMiUyQyUyMmlzRW50cnklMjIlM0F0cnVlJTJDJTIybmFtZSUyMiUzQSUyMm1haW4uanMlMjIlN0QlNUQlMkMlMjJvcHRpb25zJTIyJTNBJTdCJTIyb3V0cHV0JTIyJTNBJTdCJTIyZm9ybWF0JTIyJTNBJTIyZXMlMjIlN0QlMkMlMjJ0cmVlc2hha2UlMjIlM0F0cnVlJTdEJ …
> fix: add `PURE` tags to treeshake components

- docs/src/pages/examples/checkboxes-and-radio.mdx
When you click on the checkbox, the term value should be true.
🔎 Overview
This is a fix in the documentation.
In the example of a checkbox to accept a term, when the checkbox is checked the value is false. It should be true.
> docs: example checkbox - value should be true

- docs/src/pages/api/use-field.mdx
also removes mention of not existing `invalid` flag
🔎 __Overview__
As I said in https://github.com/logaretm/vee-validate/discussions/4271 I found this part to be confusing.
```js
// some code
```
> docs: clarify meaning of meta.valid

- docs/src/pages/api/field.mdx
- packages/vee-validate/src/Field.ts
- packages/vee-validate/tests/Field.spec.ts
- packages/vee-validate/tests/helpers/ModelComp.ts
🔎 __Overview__
This PR adds an ability to easily bind all useful props to complex components, same as it currently works with native elements.
```vue
<Field name="name" v-slot="{ componentField }">
<ComplexInput v-bind="componentField" /> // some component that expects value to be set as `modelValue` prop
</Field>
```
I was looking for such feature, as it's a bit tedious and too verbose binding all props / listeners to custom components manually. Probably there is already an easy solution that I've missed?
> Add `componentField` to Field's slot

- docs/src/pages/api/field.mdx
🔎 __Overview__
There is no `validated` property of `FieldMeta` on API Reference.
> docs: Add `validated` property to `FieldMeta`.

- packages/shared/utils.spec.ts
- packages/shared/utils.ts
- packages/vee-validate/tests/Form.spec.ts
🔎 __Overview__
Fixes https://github.com/logaretm/vee-validate/issues/4287
closes https://github.com/logaretm/vee-validate/issues/4287
> fix: respect non-POJO objects in setValues

- packages/vee-validate/src/Field.ts
🔎 __Overview__
This PR improves types for feature that is supported, but not working with TypeScript
Just noticed that binding types for `change` & `input` handlers are too narrow
The [handler](https://github.com/logaretm/vee-validate/blob/4ae1fc85481630ab6cee783348ab2f085347b2a5/packages/vee-validate/src/useField.ts#L220) itself accepts both raw value and Event, and normalizes it to the actual value
This change enables to use `field` or `componentField` bindings on components that emit raw value, not Event
Example of the error:
https://stackblitz.com/edit/vitejs-vite-assmfr?file=src%2FApp.vue,src%2Fcomponents%2FInput.vue,package.json&terminal=type-check
All functionality works, but `npm run type-check` errors about incompatible types for …
> Improve Field binding types

- .changeset/config.json
- .changeset/shiny-apricots-fix.md
- .gitignore
- packages/valibot/package.json
- packages/valibot/src/index.ts
- packages/valibot/tests/valibot.spec.ts
- pnpm-lock.yaml
- scripts/build.mjs
- scripts/config.mjs
🔎 __Overview__
[Valibot](https://github.com/fabian-hiller/valibot) seems like a nice addition especially since it is a small bundle-size alternative to yup and zod.
A few things I would like to ask/check with valibot team before releasing:
```ts
const schema = object({
name: useDefault(string(), 'test'),
age: useDefault(number(), 11),
unknownKey: optional(string()),
object: useDefault(
object({
nestedKey: optional(string()),
nestedDefault: useDefault(string(), 'nested'),
}),
{}, // <--- this has a type error even tho both keys are either optional or already have a default, which should make this object safe to be empty.
),
});
```
closes #4390
> feat: initial support for valibot

- packages/nuxt/src/module.ts
🔎 __Overview__
Add support for valibot in Nuxt
from this issue #4390
> feat(nuxt): add valibot support

- packages/i18n/src/locale/sv.json
adds `url`, `min_value`, `max_value`, `size`, and `_default` translations for `sv` locale
> adds missing translations to `sv` locale

- docs/src/pages/guide/composition-api/getting-started.mdx
🔎 __Overview__
Fix [Validating with Zod](https://vee-validate.logaretm.com/v4/guide/composition-api/getting-started/#validating-with-zod) guide wrong example.
> fix(guide): property 'required' does not exist on type 'ZodString'

- docs/package.json
- docs/src/pages/guide/composition-api/typed-schema.mdx
- packages/valibot/package.json
- packages/valibot/src/index.ts
- packages/valibot/tests/valibot.spec.ts
- pnpm-lock.yaml
Valibot is undergoing some changes as noted in #4414 and this PR aims to adapt to that once it is released along with a few enhancements suggested by the author.
- Support async schema types.
- Support the new `issues` placement on the result object instead of the inner error object.
closes #4414
> feat: update valibot support

- packages/vee-validate/src/useSetFormValues.ts
🔎 __Overview__
This PR Adds Typescript support for the `useSetFormValues` hook.
---
```ts
type Form = {
username:string
}
const setFormValues = useSetFormValues<Form>()
setFormValues({
username: 'johndoe' // we get TS autocomplete here
})
```
> chore: useSetFormValues TS Support

- docs/src/pages/guide/testing.mdx
🔎 __Overview__
This PR fixes the reference to `FormContext` and `FieldContext` in the testing page. Currently it is pointing out to `types.ts` which has been changed.
> docs: update link reference

- .changeset/mighty-melons-retire.md
- packages/vee-validate/src/types/forms.ts
- packages/vee-validate/src/useFieldArray.ts
- packages/vee-validate/src/useForm.ts
- packages/vee-validate/tests/useFieldArray.spec.ts
- packages/vee-validate/tests/useValidateField.spec.ts
> fix: avoid overriding paths and destroy path on remove

- packages/valibot/src/index.ts
- packages/valibot/tests/valibot.spec.ts
- packages/vee-validate/src/index.ts
- packages/vee-validate/src/types/forms.ts
- packages/vee-validate/src/useForm.ts
- packages/vee-validate/src/utils/common.ts
- packages/vee-validate/tests/useForm.spec.ts
- packages/yup/src/index.ts
- packages/yup/tests/yup.spec.ts
- packages/zod/src/index.ts
- packages/zod/tests/zod.spec.ts
This is preliminary support for "descriptors" for fields, which would report certain things from the schema like the field's required state for now.
I will need to support both object and array paths descriptors for the 3 main schema providers:
> feat: path descriptors for typed schemas

- docs/src/pages/examples/checkboxes-and-radio.mdx
🔎 __Overview__
An essential addition to the docs since the checkbox within a Form component is not properly usable without `unchecked-value`. It's documented nowhere.
```js
// some code
```
- https://github.com/logaretm/vee-validate/issues/3105#issuecomment-810033270
> Added the unchecked-value prop to the docs

- .changeset/shy-scissors-hug.md
- packages/vee-validate/src/useForm.ts
- packages/vee-validate/tests/useForm.spec.ts
🔎 __Overview__
Allows querying nested paths meta value by matching fields with starting path.
closes #4575
> feat: allow path meta querying for nested fields closes #4575

- packages/shared/utils.ts
- packages/vee-validate/tests/useForm.spec.ts
Fixes an issue where a target value is a POJO but the source value is not. This fix checks if both are POJOs before attempting to merge them.
This previously would've have caused crashes with Blob or File or any other JS builtin.
> fix: check if the target is POJO before attempted merge

- docs/src/pages/guide/composition-api/custom-inputs.mdx
🔎 __Overview__
Fixes a missing word.
> fix: typo in documentation (custom-inputs.mdx)

- docs/src/pages/api/use-field.mdx
Added a simple description of how to use options with useField
🔎 __Overview__
I was searching for a way to add options (type and label) to the useField function but I had to figure this out on my own since the docs were not clear enough for me.
```js
// some code
```
> Update useField docs with options

- .changeset/two-falcons-pull.md
- packages/vee-validate/src/types/forms.ts
- packages/vee-validate/src/useForm.ts
Fixes #4637 by removing the event args from handlers created by `defineField`, they were not used anyways and they only act as signals for the field to validate or apply meta changes.
> fix: remove defineField event args for component compat closes #4637

- packages/vee-validate/src/useForm.ts
- packages/vee-validate/tests/Form.spec.ts
> fix: make sure removePathState removes proper pathState

- docs/src/pages/guide/composition-api/typed-schema.mdx
Fixed Typo
🔎 __Overview__
This PR improves the documentation
```js
Fixed typo in the following line of the typed schema documentation:
"You can tell vee-validate about this information by using the typed schema resolvers available in compainion packages."
```
Changed the incorrect spelling of compainion to companion.
> Update typed-schema.mdx - fixed typo

- packages/i18n/src/locale/pt_PT.json
🔎 __Overview__
This PR adds the integer validation rule to the pt_PT translation
> refactor: add missing integer translation

- docs/src/pages/guide/i18n.mdx
- packages/i18n/src/index.ts
- packages/i18n/src/utils.ts
- packages/i18n/tests/index.spec.ts
- packages/shared/types.ts
Allow for specifying custom interpolation options for i18n. This is useful for custom interpolation patterns, such as `{{` and `}}`. Tests added, and scoped to the i18n module.
Closes #4726
🔎 __Overview__
Adds the ability to use custom interpolation options, such as prefix and suffix.
This allows the library to comply with the default i18next standard.
```js
configure({
generateMessage: localize(
'en',
{
messages: {
between: 'The {{field}} field must be between 0:{{min}} and 1:{{max}}',
},
},
{
prefix: '{{',
suffix: '}}',
},
),
});
```
closes #4726
> feat(i18n): allow custom interpolation options for i18n

- packages/rules/src/toTypedSchema.ts
- packages/vee-validate/src/types/forms.ts
- packages/vee-validate/src/useFieldState.ts
- packages/vee-validate/src/useForm.ts
- packages/vee-validate/src/useValidateField.ts
- packages/vee-validate/src/useValidateForm.ts
- packages/vee-validate/src/validate.ts
- packages/vee-validate/tests/useForm.spec.ts
- packages/yup/tests/yup.spec.ts
- packages/zod/tests/zod.spec.ts
🔎 __Overview__
This PR allows for the transformed value to pass through as the submitted value, when the transformation is declared in a field-level schema in `useField` (as opposed to a top-level schema declared in `useForm`).  This affects both Zod and Yup.
This is a revision of https://github.com/logaretm/vee-validate/pull/4692 
- ✅ Many internal types adjusted to allow for a `<TInput, TOutput>` vs `<TValues>`
- ✅ Typecheck passes
- ✅ Rebased
- ✅ All existing tests pass
- ✅ New test with zod and a new test with yup added for this behavior
```ts
// in a field component
const testRules = toTypedSchema(z.string().transform(value => value.trim()));
const { value } = useField('test', testRules);
// in a form component / page
const { handleSubmit …
```
> fix: ensure transformed values in field-level schemas are used on submit

- docs/src/pages/guide/composition-api/getting-started.mdx
🔎 __Overview__
```js
// some code
```
> docs: fix confused between validateOnModelUpdate

- .changeset/rude-rabbits-bow.md
- docs/package.json
- docs/src/components/Repl.vue
- docs/src/components/examples/CompositionInputFieldValibot.vue
- docs/src/components/examples/CompositionValibotBasic.vue
- docs/src/pages/guide/composition-api/getting-started.mdx
- docs/src/pages/guide/composition-api/typed-schema.mdx
- packages/valibot/package.json
- packages/valibot/src/index.ts
- packages/valibot/tests/valibot.spec.ts
- pnpm-lock.yaml
🔎 __Overview__
I have updated and migrated the Valibot adapter for our upcoming release.
Our migration guide: https://valibot.dev/guides/migrate-to-v0.31.0/
> I did not update the docs because I was not sure how to handle [this line](https://github.com/logaretm/vee-validate/blob/main/docs/package.json#L20). If you give me a hint, I will do it.
> feat(valibot): upgrade and migrate to v0.31.0

- packages/vee-validate/src/types/forms.ts
🔎 __Overview__
I noticed that this "property" was `undefined`, and then realised the docs don't include it so it should be removed from the types.
~It looks like the `FieldMeta` interface has `required` which doesn't exist either, but I'll do a dedicated PR to remove that~
> fix: remove non-existent `validated` property from `FormMeta` types

- docs/package.json
- packages/valibot/package.json
- pnpm-lock.yaml
Unfortunately, I introduced a breaking change in a type of Valibot v0.33.0. So I updated the dependencies.
> chore: update valibot dependency to version >=0.33.0

- docs/src/pages/guide/composition-api/custom-inputs.mdx
🔎 __Overview__
This PR fixes 2 typos:
1. `from` → `form`
2. `If it is...` → `Whether it's...` (technically not a typo, just to make it grammatically more readable)
> docs: fix typos

- docs/src/pages/guide/i18n.mdx
🔎 __Overview__
On https://vee-validate.logaretm.com/v4/guide/i18n/, you can see this following sentence:
The `\import` should be replaced by `Import`.  
```js
// some code
```
> doc: fix wording on i18N

- packages/valibot/src/index.ts
```js
// before:
safeParseAsync(valibotSchema, value)
safeParse(valibotSchema, values)
// after:
safeParseAsync(valibotSchema, value, config)
safeParse(valibotSchema, values, config)
```
> fix: allow passing valibot parsing config/option

- packages/vee-validate/src/utils/rules.ts
When creating a rule to verify that one field matches another, using the shorthand '@' prefix may return an incorrect value if the field has a falsy value, such as 0 or false.
> fix: create locator get wrong value when it is a falsy value

- packages/vee-validate/src/validate.ts
- packages/vee-validate/tests/Form.spec.ts
🔎 __Overview__
This PR improves the implementation from #{4753} by passing the context to yup when passing to form the validation schema.
Example:
```js
setup() {
const validationSchema = yup.object({
password: yup.string().required().min(3).label('Password'),
confirmPassword: yup
.string()
.required()
.oneOf([yup.ref('$password')])
.label('Confirm Password'),
});
return {
validationSchema,
};
},
template: `
<VForm  v-slot="{ errors }" :validation-schema="validationSchema">
<Field id="password" name="password" type="password" />
<span id="passwordErr">{{ errors.password }}</span>
<Field id="confirmPassword" name="confirmPassword" type="password" />
<span id="confirmPasswordErr">{{ errors.confirmPassword }}</span>
<button>Validate</button>
</VForm>
```
extends #{4753}
> feat: provide form values as context for yup schema extending #4753

- packages/valibot/package.json
- pnpm-lock.yaml
I've updated the Valibot dependency for Vee Validate to v1. We've changed the type signature, so this change is necessary. All other changes in our v1 beta version are only internal.
---
An union of schema library authors (Zod, Valibot, ArkType, ...) collaborating on a standard interface for schema libraries called [Standard Schema](https://github.com/standard-schema/standard-schema). This simplifies implementation and prevents vendor lock-in. So far Valibot v1 supports this spec and Zod will follow soon. In the long run, the explicit implementation of a Valibot and Zod adapter may no longer be necessary.
> chore: update valibot dependency to v1

- packages/vee-validate/src/utils/assertions.ts
- packages/vee-validate/tests/useForm.spec.ts
🔎 __Overview__
This PR fixes an issue where removed keys of objects in field values don't mark the form as dirty, because the `isEqual` method is not commutative. Please refer to this comment for a demonstration of the issue: https://github.com/logaretm/vee-validate/issues/4678#issuecomment-2015075349.
I read that a changeset was desired when submitting a PR, but I'm unsure what to include. Please advise.
closes #4678
(Also credits to @SCBosch)
> fix: mark form dirty when object keys are deleted

- docs/src/pages/api/use-field.mdx
🔎 __Overview__
I wrote this small piece of documentation a while ago, since then I learned that type 'text' doesn't actually exist from the TypeScript defintion of `InputType`. Type can be 'checkbox', 'radio' or 'default', so type 'text' just makes it revert to the 'default'. 
So I'd like to remove this redundant line so people don't make this mistake.
```js
// the InputType export
export type InputType = 'checkbox' | 'radio' | 'default';
```
N/A
> [Docs] Remove redundant type text

- docs/src/pages/api/use-field.mdx
🔎 __Overview__
`setValue` is a cleaner alternative to changing `field.value.value` but was never documented. I have used it extensively in my own code.
```js
const { setValue } = useField('field', value => !!value);
setValue('hello world') // sets the value and validates the field
```
N/A
> [Docs] SetValue documentation

- packages/vee-validate/src/Form.ts
- packages/vee-validate/src/devtools.ts
- packages/vee-validate/src/types/forms.ts
- packages/vee-validate/src/useForm.ts
🔎 __Overview__
This adds ability to set a `name` for a form so that it can be distinguished in the devtools.
A name can be set in the component:
```vue
<Form name="FormA">
....
</Form>
```
or in the composable:
```ts
const form = useForm({
name: "FormA"
});
```
Closes #4930
> feat: allow setting a name for the form

- packages/valibot/package.json
- pnpm-lock.yaml
We have improved the [Standard Schema spec](https://github.com/standard-schema/standard-schema). Unfortunately, this leads to a breaking change in Valibot's type signature. The implementation remains the same.
> chore: update valibot dependency

- .changeset/polite-spoons-swim.md
- packages/vee-validate/src/devtools.ts
It was noticed in #4943 that the devtools gets bundled in as a result of it being an imported dependency.
I will experiment with lazy loading it and see if it works well or not, since I do not think I can force it to be tree-shaken.
> fix(devtools): load Vue devtools lazily

- docs/src/pages/api/field.mdx
🔎 __Overview__
The types for the `field.on*` slot props of the `Field` component were changed in ce2f539, but the docs were never updated.
> docs: fix types for Field slot props

- packages/vee-validate/src/Form.ts
- packages/vee-validate/tests/Form.spec.ts
🔎 __Overview__
This PR fixes the type error in Form component's `onSubmit` prop type definition. The current implementation without type parameter for `SubmissionHandler` needs to be updated to explicitly use `GenericObject` to ensure proper type checking for form submissions.
🤓 __Code snippets/examples__
```typescript
// Type definition
export type StoreInput = z.infer<typeof storeSchema>
// Usage example causing error
<Form
:validation-schema="validationSchema"
@submit="onSubmit"  // Type '(values: StoreInput) => Promise<void>' is not assignable to type 'SubmissionHandler<GenericObject, GenericObject, unknown>'.
>
// Before
onSubmit: {
type: Function as PropType<SubmissionHandler>,
default: undefined,
},
// After
onSubmit: {
type: Function as PropType<SubmissionHandler<GenericObject>>, …
```
> fix(Form): add GenericObject type parameter to SubmissionHandler

- .changeset/angry-pens-hug.md
- packages/vee-validate/src/types/forms.ts
- packages/vee-validate/src/types/paths.ts
🔎 __Overview__
This PR aligns types of errors object destructured from useForm with the JS object that is actually returned (the issue is described in more detail in https://github.com/logaretm/vee-validate/issues/4295).
Before:
```js
type Step = {
name: string
}
type Form = {
steps: Step[]
}
type Result = Path<Form> // `steps` | `steps.${number}` | `steps.${number}.name`, fails at runtime
```
Now:
```js
type Step = {
name: string
}
type Form = {
steps: Step[]
}
type Result = Path<Form> // `steps` | `steps[${number}]` | `steps[${number}].name`, works at runtime
```
closes #4295
> fix(types): align error object types with JS object structure

- .changeset/tiny-lamps-kneel.md
- .circleci/config.yml
- packages/vee-validate/src/utils/assertions.ts
- packages/vee-validate/tests/utils/assertions.spec.ts
🔎 __Overview__
This PR fixes the custom logic inside the [`isEqual`](https://github.com/logaretm/vee-validate/blob/main/packages/vee-validate/src/utils/assertions.ts#L166-L180) function, which is used to determine whether a form is dirty.
The previous logic to compare 2 objects for equality while "ignoring" undefined values was faulty, as it would exclude from the comparison the last `n` keys of the object, where `n` is the number of undefined values found in object `a` (example 1 in the snippet below).
For cases where the second argument (`b`) would have missing keys, the logic would also fail, as it would use keys with undefined values from `a` to check if they were also present in `b` (example 2 in the snippet below).
The fix in this PR uses the original logic from …
> fix: normalize objects before equality checks

- docs/src/components/UiLibraries.vue
https://vee-validate.logaretm.com/v4/
| Before | After |
| ---- | --- |
| `<img src="/img/shadcn.svg" loading="lazy" class="dark:hidden w-24 h-24" alt="Shadcn Vue">` |  `<img src="/v4/img/shadcn.svg" loading="lazy" class="dark:hidden w-24 h-24" alt="Shadcn Vue">` |
| ![image](https://github.com/user-attachments/assets/4c829dde-75f2-4fed-8805-c6eecd59ff6f) | ![image](https://github.com/user-attachments/assets/16d12c33-b0e1-4743-82f1-a4d2f6f37a0f) |
> Fix shadcn-vue image in documentation

- .changeset/famous-wombats-tan.md
- packages/valibot/src/index.ts
- packages/valibot/tests/valibot.spec.ts
🔎 __Overview__
I use the `required` field on `useField#meta` to automatically show an "Optional" text on an input. I found that having intersections in Valibot breaks this. For example, I have a PasswordSchema for reusability:
```ts
export const PasswordSchema = v.pipe(
v.object({
password: v.pipe(v.string(), v.minLength(8)),
confirmPassword: v.pipe(v.string(), v.minLength(8)),
}),
v.forward(
v.partialCheck(
[['password'], ['confirmPassword']],
(input) => input.password === input.confirmPassword,
'The two passwords do not match.',
),
['confirmPassword'],
),
)
```
Which I then use in a form:
```ts
const schema = v.object({
user: v.intersect([
PasswordSchema,
v.object({
email: v.pipe(v.string(), v.email()),
}),
]),
})
```
This resulted in `required` always being `true`.
I've implemented a …
> fix: valibot intersections

- .changeset/angry-eels-confess.md
- packages/valibot/src/index.ts
- packages/valibot/tests/valibot.spec.ts
🔎 __Overview__
Similar to https://github.com/logaretm/vee-validate/pull/5014
I use the required field on useField#meta to automatically show an "Optional" text on an input. I found that having `v.variant` breaks this.
> fix: valibot variants not inferring required correctly

- docs/src/pages/guide/components/handling-forms.mdx
This PR fixes the code sample in the “Handling Submissions” section of the Vee-Validate docs. The original snippet mistakenly self-closed the `<Form>` tag and mismatched `name`/`type` attributes on `<Field>` components, causing fields not to be included in the form and improper validation rules to apply.
- Wrapped the `<Form>` tag properly so that all `<Field>`s and the `<button>` live inside it.
- Moved `type="email"` to the email field and left other fields as default text.
- Added `type="submit"` to the `<button>` for clarity and safety.
```html
<Form method="post" action="/api/users" :validation-schema="schema" />
<Field name="email" />
<Field name="name" type="email" />
<Field name="password" type="password" />
<button>Submit</button>
</Form>
> docs: fix Handling Submissions example Form tag

- docs/src/pages/guide/composition-api/typed-schema.mdx
🔎 __Overview__
This PR fixes a missing comma in the "valibot" usage documentation code snippet that was causing invalid syntax. This ensures the example code is correct and can be properly executed.
> chore(docs): fix missing comma typo
