src/fieldBag.js
test/fieldBag.js

Removed the use of Proxy()
Updated tests
DID NOT generate the dist/ (some problem with rollup)

Removed Proxy()

---

__tests__/validator.js
src/validator.js

Fix for issue #67. Am I supposed to run `npm run build` for these PRs?

Fix normalize rule to handle multiple colons.

---

__tests__/listeners.js

If the tests need cleaning up, go for it. :)

More test coverage for listeners.js

---

src/listeners.js

The only thing that was changing was the value for 99% of the calls. I didn't add any tests for the change.

DRY calls to validator

---

src/listeners.js

This fixes the error `el is not defined` and files not being rejected.

Fix file not being rejected

---

dist/vee-validate.js
src/directive.js

Check for undefined before attempting to access ‘instance’ property.

---

__tests__/validator.js
src/validator.js

This will create an append method on the validator to be able to append an extra validation to a specific field.
It merges the to validations with the field together with the validations from the parameter and sends that to the attach method.
Matching tests have been written too.

Create append validation

---

package.json
types/index.d.ts

The typescript defintion should be added to package.json
to enable automatic resolving to the defintion file.
I haved added an index.d.ts to export both definitions and updated package.json
to reference the index defintion.
https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html

added typings definition to package

---

types/vee-validate.d.ts

Remove references to moment

---

locale/fr.js

Fix translation errors from #429
Contribute to #428

#428 Fix translation error for french locale

---

locale/et.js

The locale definition includes a function for first letter capitalization, since the subject is often the first word in Estonian.

Add Estonian locale

---

src/classes.js
src/validator.js

Fix auto classes not working on components. 
(Not sure why you specifically removed this, but I use it and need it)

Fix global scope flagging

---

locale/ua.js

Ukraine ISO https://en.wikipedia.org/wiki/ISO_3166-2:UA

Update and rename uk.js to ua.js

---

docs/src/templates/markdown/examples/flags.md

Hi,
Fixed typo > "tocuhed" to "touched" in Flags doc.

fix typo > "tocuhed" to "touched"

---

locale/hr.js

Croatian language added. 
By all means I'm not a native Croatian speaker so fell free to fix my messages.

Croatian language

---

docs/examples.html

added additional check of valditation result in examples inside Documentation (To reflect current issue in Documentation and prevent further confusion). Reflecting the solution for this issue inside Documentation. https://github.com/logaretm/vee-validate/issues/592

added additional check of valditation result in Documentation examples

---

locale/nl.js

Fix Dutch size rule translation

---

docs/src/templates/markdown/rules/validations.md

https://github.com/baianat/vee-validate/pull/650#issuecomment-317055061
Sorry, didn't see that. Thx for the info!

Update rules regarding date_format can be globally set

---

locale/sr.js

Added Serbian cyrillic localization file sr.js

Create sr.js locale

---

locale/da.js

Added validation messages for _default and alpha_spaces

Added validation messages

---

docs/index.html

only a few small spelling mistakes corrected

fixed spelling in Index.html

---

locale/sr.js

Fix locale name

---

package.json
types/vee-validate.d.ts

Updated TypeScript Definitions for RC8.

TypeScript Definitions RC8

---

README.md
docs/src/templates/markdown/api.md

• Compatibility instead of Compatability
• Closes #779 , closes #783

Fix README.md typo

---

types/tests/tsconfig.json
types/vee-validate.d.ts

Please add ":void" on "updade" method.

tsc "void" declaration

---

locale/tr.js

old message is mean , must be maximum {number} digits
fix to this field equals to {number} digits

turkish digits message fix

---

locale/pt_PT.js

Add European Portuguese translation, based on the existing Brazilian Portuguese translation

Add pt_PT translation

---

.babelrc
package.json
src/core/validator.js
tests/validator.js

closes #858 
Sorry, I have to add babel because I can't run test with async, await function.

Add array parameter for validateAll function

---

docs/index.html

I noticed a couple of little things that could be better on the index page and figured I'd lend a hand.

grammar and spelling corrections in docs

---

locale/id.js

Adding data messages for _default, alpha_spaces, credit_cart, integer and length.

Update data messages for id.js

---

README.md

Just fixed a few of the more glaring punctuation or verb tense issues. I tried to keep it minimal, so accept if you like.

Add some minor improvements to the readme

---

README.md

File names are case sensitive. Updated link to CONTRIBUTING.md in the READEME file

Fix link to the contribution guide in README.md

---

docs/src/templates/markdown/rules/validations.md

Added documentation for required:invalidateFalse

---

locale/sq.js

International language code for Albanian is sq.

Add Albanian language

---

types/vee-validate.d.ts

updated typescript definitions

---

src/install.js

allows for multiple installs on different Vue classes when not in production

---

.babelrc
locale/ko.js
package.json

To keep the Korean rules up to date

Add new rules to locale/ko.js

---

locale/zh_CN.js
locale/zh_TW.js

the new message for decimal will be better

the locale for zh_CN and zh_TW

---

src/core/field.js
src/core/validator.js
src/install.js
tests/unit/errorBag.js
tests/unit/fieldBag.js
tests/unit/validator.js

This PR applies the usage of internal Vue instance to manage events and nextTick callbacks.

Use Vue instance

---

src/core/validator.js
tests/unit/validator.js
types/vee-validate.d.ts

Details: https://github.com/baianat/vee-validate/issues/1243

Add silent validation run

---

build/esm.js
src/rules/index.js

separate bundle for rules

---

docs/api/data-attrs.md

Looks prettier if word doesn't break

Left column permit word breaking

---

docs/configuration.md

Fix configuration.md

---

locale/lv.js

Latvian language support.

---

docs/guide/events.md

docs: update docs for validation events

---

docs/api/validator.md

the promise is very useful, therefore I would like to add documentation to help people using it :)

add more description on the validate Promise

---

docs/examples/locale.md

I added an example for async localization, feel free to add my example to your codesandbox project.

docs: add async localization example

---

locale/fr.js

Add integer et length messages

locale: update french translation

---

locale/fa.js

Add missing `default` message for persian/farsi

Add missing `default` message for persian/farsi

---

src/rules/regex.js
tests/unit/rules/regex.js

Added support to handle regex rule for array field.

feat: handle array for regex rule closes #1577

---

locale/zh_CN.js

zh_CN message for length rule.

---

locale/zh_CN.js

improve the message for length rule.

fix zh_CN message for length rule

---

locale/lv.js

Changes are made to better express missing fields data

Change some Latvian translation strings

---

docs/guide/rules.md

Docs: Updates documenation for "confirmed" rule

---

locale/ja.js

Changed message of date_format

fix ja messages

---

locale/pl.js

__ 🔎 Overview__
Polish locale haven't _default message and a few others.

Update pl.js - add missing messages

---

docs/api/data-attrs.md

This commit documents the "data-vv-scope" attribute.

Add docs for "data-vv-scope" attribute

---

locale/de.js

🔎 __Overview__
Updating german rule translations to include latest set of rules.

feat(locale): update german translations

---

docs/api/field.md

very small change
🔎 __Overview__
Ex (Feat):
Ex (Locale):
```js
// some code
```

removed extra )

---

docs/guide/rules.md

🔎 __Overview__
Ex (Feat):
Ex (Locale):
```js
// some code
```

fix: url example with require_protocol

---

types/vee-validate.d.ts

🔎 __Overview__
> This PR fixes the bug related on the issue : #1830

Fix typescript definition error in vee-validate.d.ts

---

locale/mn.js

🔎 __Overview__
Adding support for Mongolian language

locale: mongolian translation

---

src/components/provider.js

This PR introduces a cache for the debounced handler as on each render-cycle a new one is created, which does not cancel the previously triggered validation that should be debounced.
closes #1846

fix: cache the debounced handler closes #1846

---

docs/guide/ui-integrations.md

🔎 __Overview__
Docs:
> This PR add another example into ui-integrations part.
This example use vee-validate as "global validation system"
[codesandbox example](https://codesandbox.io/s/mxow346yj?autoresize=1&hidenavigation=1&module=%2Fsrc%2FApp.vue&view=preview)

docs(ui-integrations): add vue-form-json

---

docs/guide/components/validation-observer.md

🔎 __Overview__
Ex (Feat):
Ex (Locale):
```js
// some code
```

Fixed documentation for errors

---

src/components/observer.js
src/components/provider.js

fix: handle component activation/deactivation via keep-alive

---

docs/configuration.md

🔎 __Overview__
Ex (Feat):
Ex (Locale):
```js
// some code
```

add useConstraintAttrs to configuration docs

---

docs/guide/rules.md

update the date-fns format link to reflect the latest changes merged by #1698

docs: update date format link

---

docs/guide/interaction.md

🔎 __Overview__
Fix typos in interaction.md

Fix typos with interaction.md

---

locale/ro.js

🔎 __Overview__
Ex (Feat):
Ex (Locale):
```js
// some code
```

Final updates

---

types/vee-validate.d.ts

Fix for https://github.com/baianat/vee-validate/issues/2004

Statements are not allowed in ambient contexts (#2004)

---

types/index.d.ts
types/vee-validate.d.ts

Hello,
I have update the types definition.
> This PR fixes/improves the typescript implementation
Thanks.

fix: fix types definitions

---

locale/ar.js

🔎 __Overview__
Edit error message for email validation to e more natural and readable

Update email validation message

---

locale/hi.js

🔎 __Overview__
Hello,
I have provided Hindi configuration for internationalization.
Thanks.

Add Hindi config

---

src/index.minimal.esm.js

Closes #2044
🔎 __Overview__
This PR exposes custom mode feature for consumers using minimal bundle size method.
closes #2044

feat: setMode in minimal bundle size usage method of the lib (#2044)

---

locale/sv.js

adding _default value
closes #2070

Update sv locale

---

types/vee-validate.d.ts

🔎 __Overview__
Ex (Feat):
> This PR fixes the bug of types declaration issue
> closes #{2096}

Fix types: export Rules as const

---

locale/en.js
locale/it.js

🔎 __Overview__
There were wrong messages in it and en validation rule for decimal.
> This PR changes the it and en messages to fix the issue.
> closes #2140

fix: updated wrong message in it and en decimal validation rule

---

docs/examples/backend.md
docs/guide/advanced-validation.md
docs/guide/interaction-and-ux.md
docs/guide/validation-observer.md
docs/guide/validation-provider.md

I've recently read all the docs, and found some mistakes. 
Going to fix them in this PR. 
Once I done, I'll notice owner of this repository.

Fix mistakes in recently released docs

---

docs/guide/validation-provider.md

🔎 __Overview__
Fixed just a small mardown error.

fixed validation-provider props table

---

README.md

🔎 __Overview__
Ex (DOCS):
file: README.md
The link in the phrase "Many rules are available out of the box" was broken. i change
https://logaretm.github.io/vee-validate/guide/rules.html  to
https://logaretm.github.io/vee-validate/api/rules.html
the rules list link of the package description in npm has an  404 error. (https://www.npmjs.com/package/vee-validate)

Update Link to rules list in Readme.md

---

docs/.vuepress/components/StyledProvider.vue

🔎 __Overview__
Docs input has incorrect offsets
https://monosnap.com/file/FvZsQkt76TFUjoo9oeJVxSLJ5wjdcy
Ex (Feat):
> This PR Update input and select styles for fix offset
https://monosnap.com/file/5LhmREiRn4aOMZ0qGmLNfIIGTmOHv4

Fix input and select offsets

---

docs/guide/displaying-errors.md
docs/guide/localization.md

🔎 __Overview__
Fix broken string interpolation example.
Introduced in 135a44a
None

docs: fix broken example

---

package.json
scripts/replaceDefs.js
src/components/common.ts
src/components/withValidation.ts
src/rules/alpha_helper.ts
tests/config.spec.js
tests/providers/lifecycle.spec.js
tests/providers/provider.js
tsconfig.json

🔎 __Overview__
Ex (Fix):
> This PR fixes lint script in package.json and eslint issues that appeared after fix

fix: update eslint script and fix all the issues

---

docs/guide/forms.md

🔎 __Overview__
fixed spelling mistakes and added some structural improvements to make the text more understandable.
Ex (Feat):
> This PR fixes spelling mistakes and improves the grammatical structure of the documentation (forms).

Spelling corrections in forms.md

---

docs/guide/rules.md

🔎 __Overview__
Ex (Feat):
Ex (Locale):
```js
// some code
```

docs: added warning in required_if and fixed misspelling

---

docs/guide/localization.md

🔎 __Overview__
Ex (Feat):
Ex (Locale):
```js
// some code
```

docs: update links for version 2

---

docs/guide/basics.md

🔎 __Overview__
Fix a typo in documentation.

Fix typo in doc

---

src/rules/alpha_helper.ts

🔎 __Overview__
This PR tries to add greek support for alpha rules.
closes #2778

Add greek support for alpha rules

---

packages/core/src/Field.ts
packages/core/src/Form.ts
packages/core/src/types.ts
packages/core/src/useField.ts
packages/core/src/useForm.ts
packages/core/src/utils/assertions.ts
packages/core/tests/Form.spec.ts
packages/core/tests/helpers/index.ts
packages/docs/components/DocMenu.vue
packages/docs/content/examples/checkboxes-and-radio.md
packages/docs/layouts/default.vue

This PR adds support for `type="checkbox"` and `type="radio"` for HTML inputs.

feat(v4): add checkbox and radio HTML input support

---

docs/advanced/refactoring-forms.md

docs: fix a typo on refactoring-forms

---

src/rules/length.ts
tests/providers/provider.js

🔎 __Overview__
Ex (Feat):
This PR is an small improvment of my last PR. It does not convert numbers to strings and then to array.
Removed one unneded id introduced by my PR
Ex (Locale):

fix: don't convert numbers to array

---

package.json
packages/core/package.json
yarn.lock

🔎 __Overview__
Ex (Feat): Introduce workspaces to resolve dependency issues.
The `next` branch uses a workspaces-like folder structure but does not actually utilize workspaces feature in Yarn. This results in `vue` being unknown for IDE autocompletion. This PR attempts to fix that.
After the change `vue` is resolved on a workspace global level.

feat: workspaces

---

docs/components/global/CodeSandbox.vue
docs/content/examples/custom-inputs.md
docs/content/guide/global-validators.md

- Added documentation for the global validators along with an example for each one
- Added a dynamic playground for validation rules

docs: rules documentation

---

packages/core/src/Field.ts
packages/core/src/useField.ts
packages/core/tests/helpers/index.ts
yarn.lock

Now it checks the checkbox `checked` attr first before toggling it. pun intended.
closes #2936

fix: avoid toggling checkbox `checked` attr in `handleChange`

---

docs/content/api/use-form.md

🔎 __Overview__
Fixes an example in the docs of `useForm`

docs: fix setFieldError/setErrors examples

---

docs/content/guide/overview.md

🔎 __Overview__
Ex (Feat):
Ex (Locale):
```js
// some code
```

docs: fixed spelling in overview

---

docs/content/api/form.md

🔎 __Overview__
This PR fixes a docs typo.

docs: fix typo

---

docs/api/validation-observer.md

This PR updates the docs related to this PR which was merged recently:
https://github.com/logaretm/vee-validate/pull/3019

Docs - update info about observer 'disabled' prop

---

locale/es.json

🔎 __Overview__
Ex (Feat):
Ex (Locale):
```js
// some code
```

Add is and is_not key ESP traslate

---

docs/content/api/composition-helpers.md
docs/content/api/use-form.md
docs/content/guide/composition-api.md
packages/vee-validate/src/index.ts
packages/vee-validate/src/types.ts
packages/vee-validate/src/useForm.ts
packages/vee-validate/src/useSubmitForm.ts
packages/vee-validate/tests/useResetForm.spec.ts
packages/vee-validate/tests/useSubmitForm.spec.ts

Adds `useSubmitForm` to the list of composition helpers

feat: added useSubmitForm hook

---

docs/advanced/server-side-validation.md

🔎 __Overview__
This update's one word in the docs. It's a minor issue ;-).

Change name field's name to name ;-)

---

docs/content/guide/handling-forms.md

!error
<Field name="email" as="input" />
<Field name="name" as="input" type="email" />
Fixed!
🔎 __Overview__
Ex (Feat):
Ex (Locale):
```js
// some code
```

The example was updated  in handling-forms.md

---

docs/content/guide/components/validation.md

found typo and added space
🔎 __Overview__
just found typo.
Ex (Feat):
Ex (Locale):
```js
// some code
```
i don't think this commit affect any issues.

update validation.md(fixing typo)

---

docs/content/api/field.md
packages/vee-validate/src/Field.ts
packages/vee-validate/src/utils/assertions.ts
packages/vee-validate/src/utils/events.ts
packages/vee-validate/src/utils/vnode.ts

feat: added value change support for native multi select

---

src/components/Provider.ts

🔎 __Overview__
```js
// some code
```

Added name for ValidationProvider component

---

packages/i18n/src/locale/cy.json

Add Welsh-language translations

---

docs/content/guide/components/validation.md

Fix element missing end tag.

---

src/rules/alpha_helper.ts

🔎 __Overview__
This PR tries to add japanese supoort for alpha rules
closes #3327

Add japanese support for alpha rules

---

docs/overview.md

fix grammatical errors in first / intro paragraph
🔎 __Overview__
This PR fixes some of the grammatical errors in the overview page.

fix(overview): Grammar in intro paragraph

---

src/rules/alpha_helper.ts

🔎 __Overview__
Closes https://github.com/logaretm/vee-validate/issues/3357
New regex:

Fix japanese validations

---

packages/i18n/src/index.ts
packages/i18n/tests/index.spec.ts

fix(i18n): field name in default error message

---

locale/tr.json

Add missing Turkish locale translations

---

docs/components/DocFlavor.vue

🔎 __Overview__
```js
// some code
```

Update DocFlavor.vue. Fix small typo.

---

docs/content/api/composition-helpers.md
docs/content/guide/overview.md

Just some stylistic improvements to the documentation ;-)
Btw there are errors in the examples on this page: https://vee-validate.logaretm.com/v4/guide/composition-api/validation

docs: stylistic improvements to overview

---

packages/i18n/src/locale/uz.json

Added 'uz' - Uzbekish language

Created uz.json file

---

locale/uz.json

Created uz.json (Uzbek language) file.

---

docs/content/integrations/zod-schema-validation.md

🔎 __Overview__
This PR fixes the doc (#3674).

Fix sample codes in Zod Schema Validation page

---

packages/i18n/src/locale/so.json

Adding locale for Somali language

Add Somali locale

---

packages/i18n/src/locale/tr.json

This PR adds some missing Turkish translations.

Add missing Turkish translations

---

packages/vee-validate/src/index.ts

🔎 __Overview__
This PR exports `InvalidSubmissionHandler` and `GenericValidateFunction` types to make the following possible.
```ts
const customValidator: GenericValidateFunction = (val, ctx) => {}
//                     ^^^^^^^^^^^^^^^^^^^^^^^
const { handleSubmit } = useForm<Form>(/* ... */)
const submit: SubmissionHandler<Form> = (form, ctx)  => {}
const handleInvalidSubmit: InvalidSubmissionHandler<Form> = (ctx) => {}
//                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
const triggerSubmit = handleSubmit(submit, handleInvalidSubmit)
```

feat: Expose InvalidSubmissionHandler and GenericValidateFunction types

---

docs/content/api/use-form.md

it was a typo mistake "If ou try " which has been changed to "If you try"
🔎 __Overview__

Typo mistake

---

packages/vee-validate/src/useFieldState.ts
packages/vee-validate/tests/useField.spec.ts

fix: reset the original value when resetField is called #3891

---

docs/src/pages/api/use-field.mdx

🔎 __Overview__
this PR fix wrong content on setErrors section to correct resetField section

chore(docs): fix wrong content on setErrors

---

packages/i18n/src/locale/cs.json

..to be inline with existing EN localization
🔎 __Overview__
This PR adds missing CS messages

Update CS (Czech) localization

---

packages/i18n/src/locale/sk.json

..to be inline with existing EN localization
🔎 __Overview__
This PR adds missing SK messages

Update SK (Slovak) localization

---

docs/src/pages/api/field.mdx

Change `reieve` to `receive`.
🔎 __Overview__
```js
// some code
```

Fix typo in field.mdx

---

packages/i18n/src/locale/cs.json

🔎 __Overview__
This PR fixes the wrong placeholder in CS localization

fix: wrong placeholder in CS localization

---

docs/src/pages/guide/i18n.mdx

🔎 __Overview__
The anchor to the localization section in yup's README.md has changed, this PR links to the new section.

Updated link to yup's localization guide

---

docs/src/pages/guide/overview.mdx

🔎 __Overview__
```js
// some code
```

Update overview.mdx - Add pnpm example

---

docs/api/validation-observer.md

🔎 __Overview__
Makes v3 docs more understandable.

fix: clarity and potential typo

---

docs/src/pages/tutorials/dynamic-form-generator.mdx

Type of "formSchema" is JavaScript Object, it's not JSON

Change schema type name from JSON to js object

---

.changeset/config.json
.changeset/metal-buckets-grin.md
docs/src/pages/integrations/nuxt.mdx
packages/nuxt/README.md
packages/nuxt/package.json
packages/nuxt/src/module.ts
pnpm-lock.yaml
scripts/build.mjs

🔎 __Overview__
Adds a nuxt module packages that does the following:
- Auto imports for all composables within vee-validate
- Auto imports for all components within vee-validate
Still need to support other packages like i18n if needed.
closes #4071

feat: Nuxt module

---

package.json
pnpm-lock.yaml
scripts/build.mjs
scripts/config.mjs
scripts/generate-dts.mjs
scripts/normalize-path.mjs

🔎 __Overview__
This repo cannot be built on Windows machines.
This PR fixes the Windows build from this comment: https://github.com/logaretm/vee-validate/issues/4339#issuecomment-1613136426

chore: fix local build on Windows

---

packages/nuxt/package.json

🔎 __Overview__
Fix nuxt package exports.

chore: fix nuxt package exports

---

packages/vee-validate/src/index.ts

🔎 __Overview__
```js
// some code
```

chore: exports type formerrors

---

docs/src/pages/tutorials/basics.mdx

demo of basic example is 404.
updated id to display expected demo（https://stackblitz.com/edit/vitejs-vite-2ia3j4?file=index.html）

docs:Update basic example demo

---

packages/nuxt/src/module.ts

🔎 __Overview__
Solves issue #4543

feat(nuxt): added typedSchemaPackage option to resolve conflicts

---

.changeset/violet-apes-tan.md
packages/rules/src/email.ts
packages/rules/tests/email.spec.ts

fix: use a better email re pulled from zod closes #4585

---

.changeset/angry-steaks-itch.md
packages/yup/src/index.ts
packages/yup/tests/yup.spec.ts

fix: use spec to find required state 

---

packages/vee-validate/src/useForm.ts
packages/vee-validate/tests/useField.spec.ts

not removing paths which were re-created between unset schedule and dispatch
closes #4603

fix: unset paths

---

docs/src/pages/examples/using-stores.mdx

This PR adds a couple of lines to the Pinia documentation page to describe a known issue as described in this comment.
https://github.com/logaretm/vee-validate/issues/4519#issuecomment-1819879822

Add a warning to the Pinia documentation page

---

docs/src/pages/guide/composition-api/typed-schema.mdx

🔎 __Overview__
Update docs to use new API
```js
// some code
```

docs: change deprecated valibot withDefault to optional

---

docs/src/pages/integrations/zod-schema-validation.mdx

Method has been deprecated for a while. min(1) is the suggested replacement. https://github.com/colinhacks/zod/discussions/2847
🔎 __Overview__
Updates docs to align with zod. Package does not add additional methods to zod.
No issues

docs: replaces deprecated zod.nonempty() with zod.min(1)

---

docs/src/pages/api/form.mdx

Fkixing a word that was misspelled
🔎 __Overview__
```js
// some code
```

fix: minor typo

---

docs/src/pages/api/use-field.mdx

Fixing a minor typo error
🔎 __Overview__
```js
// some code
```

Fixing a minor typo error

---

docs/src/pages/guide/composition-api/getting-started.mdx

🔎 __Overview__
This PR fixes a broken link

docs: fix Link

---

packages/yup/package.json

Sorry, the previous edit missed a comma.
🔎 __Overview__
```js
// some code
```

Update package.json yup should be a peerdependences

---

docs/src/pages/guide/composition-api/getting-started.mdx

🔎 __Overview__
This PR removes redundant text to improve readability.

docs : Improve Readability

---

docs/src/pages/api/form.mdx
docs/src/pages/api/use-form.mdx
docs/src/pages/guide/devtools.mdx

🔎 __Overview__
Adds documentation around the new `name` prop

Documentation for new `name` prop

---

docs/src/pages/api/field.mdx
docs/src/pages/guide/composition-api/typed-schema.mdx
docs/theme.json
packages/rules/tests/alpha.spec.ts
packages/rules/tests/alpha_dash.spec.ts
packages/rules/tests/alpha_num.spec.ts
packages/rules/tests/alpha_spaces.spec.ts

🔎 __Overview__
This PR improves some minor typos in the docs and other code.

chore: fix typos
